export interface Puzzle {
  id: number;
  formal: string;         // The bureaucratic translation shown to the player
  answer: string;         // Primary correct answer (canonical)
  accepted: string[];     // All acceptable answers (fuzzy matched against these)
  artist: string;         // Revealed as hint 3
  era: string;            // e.g. "1980s" — revealed as hint 1
  genre: string;          // e.g. "Pop" — revealed as hint 4
  firstLetters: string;   // e.g. "T M H C R" — revealed as hint 2
  difficulty: 'easy' | 'medium' | 'hard' | 'extra-hard';
  dayOfWeek?: number;     // 1=Monday, 7=Sunday — for difficulty curve scheduling
}

// ─── Bonus puzzles — extra-hard, one per week ────────────────────────────────
// IDs 101–130 reserved for bonus puzzles
export const bonusPuzzles: Puzzle[] = [
  // FIXED: Previously translated song theme/lyrics (can't leave, extended residency).
  // Changed to direct title-word translation: Hotel → Hospitality Establishment, California → State Of California.
  {
    id: 101,
    formal: "Hospitality Establishment Situated Within The Jurisdictional Boundaries Of The State Of California",
    answer: "Hotel California",
    accepted: ["hotel california"],
    artist: "Eagles",
    era: "1970s",
    genre: "Rock",
    firstLetters: "H C",
    difficulty: "extra-hard",
    dayOfWeek: 7,
  },
  // FIXED: Previously translated lyrics (jealousy, surveillance, romantic pursuit).
  // Changed to direct title translation: Mr. → Male Individual, Brightside → Optimistic Outlook.
  {
    id: 102,
    formal: "Formal Salutation Directed Toward A Male Individual Distinguished By A Characteristically Optimistic Dispositional Outlook",
    answer: "Mr. Brightside",
    accepted: ["mr brightside", "mr. brightside", "mister brightside"],
    artist: "The Killers",
    era: "2000s",
    genre: "Indie Rock",
    firstLetters: "M B",
    difficulty: "extra-hard",
    dayOfWeek: 7,
  },
  // FIXED: Previously translated lyrics (rains, romantic history).
  // Changed to direct title translation: Africa → Continental Landmass.
  {
    id: 103,
    formal: "The Sub-Saharan Continental Landmass Constituting The Second Largest Geographical Division Of The Eastern Hemisphere",
    answer: "Africa",
    accepted: ["africa"],
    artist: "Toto",
    era: "1980s",
    genre: "Pop / Rock",
    firstLetters: "A",
    difficulty: "extra-hard",
    dayOfWeek: 7,
  },
  // FIXED: Previously translated lyrics (prostitution, red light).
  // Replaced with "Stairway To Heaven" as extra-hard bonus (Roxanne is just a name).
  // Moved old Stairway (ID 33) here as extra-hard and replaced ID 33 with new puzzle.
  {
    id: 104,
    formal: "A Grand Ascending Architectural Structure Comprised Of Sequential Horizontal Platforms Providing Progressive Vertical Access To The Elevated Celestial Realm Of Eternal Beatitude",
    answer: "Stairway To Heaven",
    accepted: ["stairway to heaven"],
    artist: "Led Zeppelin",
    era: "1970s",
    genre: "Rock",
    firstLetters: "S T H",
    difficulty: "extra-hard",
    dayOfWeek: 7,
  },
  // FIXED: Previously translated lyrics (structural barrier, personal deterioration).
  // Changed to direct title translation: Wonder + Wall.
  {
    id: 105,
    formal: "A Vertical Structural Partition Evoking An Overwhelming Sense Of Astonishment, Reverence, And Profound Bewilderment",
    answer: "Wonderwall",
    accepted: ["wonderwall"],
    artist: "Oasis",
    era: "1990s",
    genre: "Britpop",
    firstLetters: "W",
    difficulty: "extra-hard",
    dayOfWeek: 7,
  },
  // FIXED: Previously translated lyrics (song, biographical data).
  // Changed to direct title translation: Killing + Me + Softly.
  {
    id: 106,
    formal: "The Gradual Termination Of The Speaker's Biological Existence Conducted In A Characteristically Gentle And Subdued Manner",
    answer: "Killing Me Softly",
    accepted: ["killing me softly", "killing me softly with his song"],
    artist: "Roberta Flack / Fugees",
    era: "1970s",
    genre: "Soul / R&B",
    firstLetters: "K M S",
    difficulty: "extra-hard",
    dayOfWeek: 7,
  },
  // FIXED: Previously translated theme (chaotic conduct).
  // Changed to direct title translation: Livin' + La Vida Loca (The Crazy Life).
  {
    id: 107,
    formal: "The Sustained Practice Of Maintaining One's Biological Existence Within A Mode Of Living Characterised By Pronounced Psychological Instability And Irrational Exuberance",
    answer: "Livin' La Vida Loca",
    accepted: ["livin la vida loca", "living la vida loca", "livin' la vida loca"],
    artist: "Ricky Martin",
    era: "1990s",
    genre: "Latin Pop",
    firstLetters: "L V L",
    difficulty: "extra-hard",
    dayOfWeek: 7,
  },
  // FIXED: Previously translated theme (competitor primed for combat).
  // Changed to direct title translation: Eye + Of + The + Tiger.
  {
    id: 108,
    formal: "The Singular Ocular Apparatus Belonging To A Large Predatory Feline Of The Genus Panthera Tigris",
    answer: "Eye of the Tiger",
    accepted: ["eye of the tiger"],
    artist: "Survivor",
    era: "1980s",
    genre: "Rock",
    firstLetters: "E T",
    difficulty: "extra-hard",
    dayOfWeek: 7,
  },
  // FIXED: Previously over-interpreted (astronomical body, exceptional character).
  // Changed to direct title translation: All + Star.
  {
    id: 109,
    formal: "A Universal Inclusive Classification Designating Each And Every Individual As A Premier Performer Of The Highest Competitive Calibre",
    answer: "All Star",
    accepted: ["all star", "allstar"],
    artist: "Smash Mouth",
    era: "1990s",
    genre: "Pop Rock",
    firstLetters: "A S",
    difficulty: "extra-hard",
    dayOfWeek: 7,
  },
  // FIXED: Previously translated lyrics (bar setting, emotionally compromised patrons).
  // Changed to direct title translation: Piano + Man.
  {
    id: 110,
    formal: "An Adult Male Individual Professionally Employed In The Regular Operation Of A Large Keyboard Percussion Instrument",
    answer: "Piano Man",
    accepted: ["piano man"],
    artist: "Billy Joel",
    era: "1970s",
    genre: "Pop / Rock",
    firstLetters: "P M",
    difficulty: "extra-hard",
    dayOfWeek: 7,
  },
  // FIXED: Previously translated theme (emotional disorientation).
  // Changed to direct title translation: Total + Eclipse + Of + The + Heart.
  {
    id: 111,
    formal: "A Comprehensive And Unqualified Astronomical Obscuration Event Affecting The Entirety Of The Primary Cardiac Organ",
    answer: "Total Eclipse of the Heart",
    accepted: ["total eclipse of the heart"],
    artist: "Bonnie Tyler",
    era: "1980s",
    genre: "Power Ballad",
    firstLetters: "T E H",
    difficulty: "extra-hard",
    dayOfWeek: 7,
  },
  // FIXED: Previously translated lyrics (day the music died, plane crash).
  // Changed to direct title translation: American + Pie.
  {
    id: 112,
    formal: "A Baked Pastry Confection Enclosed Within A Structured Crust, Of Unambiguous United States Provenance And Cultural Significance",
    answer: "American Pie",
    accepted: ["american pie"],
    artist: "Don McLean",
    era: "1970s",
    genre: "Folk Rock",
    firstLetters: "A P",
    difficulty: "extra-hard",
    dayOfWeek: 7,
  },
  // FIXED: Previously translated lyrics (I'm a weirdo, unattainable person).
  // Changed to direct title translation: Creep.
  {
    id: 113,
    formal: "An Individual Whose Habitual Conduct Is Characterised By Socially Inappropriate, Unsettling, And Furtive Behavioural Patterns",
    answer: "Creep",
    accepted: ["creep"],
    artist: "Radiohead",
    era: "1990s",
    genre: "Alternative Rock",
    firstLetters: "C",
    difficulty: "extra-hard",
    dayOfWeek: 7,
  },
  // FIXED: Previously translated lyrics (territorial allegiance, cultural pride).
  // Changed to direct title translation: Sweet + Home + Alabama.
  {
    id: 114,
    formal: "An Agreeable Primary Residential Domicile Situated Within The Jurisdictional Boundaries Of The Southeastern State Of Alabama",
    answer: "Sweet Home Alabama",
    accepted: ["sweet home alabama"],
    artist: "Lynyrd Skynyrd",
    era: "1970s",
    genre: "Southern Rock",
    firstLetters: "S H A",
    difficulty: "extra-hard",
    dayOfWeek: 7,
  },
  // FIXED: Previously translated lyrics (romantic locomotion).
  // Changed to direct title translation: Like + A + Prayer.
  {
    id: 115,
    formal: "Bearing A Marked Phenomenological Resemblance To A Formal Devotional Supplication Directed Toward A Supreme Ecclesiastical Entity",
    answer: "Like a Prayer",
    accepted: ["like a prayer"],
    artist: "Madonna",
    era: "1980s",
    genre: "Pop",
    firstLetters: "L P",
    difficulty: "extra-hard",
    dayOfWeek: 7,
  },
  // NEW bonus puzzles
  {
    id: 121,
    formal: "A Theatrical Dramatic Musical Composition Performed In The Stylistic Tradition Of A Free-Spirited Nonconformist Individual From Central Europe",
    answer: "Bohemian Rhapsody",
    accepted: ["bohemian rhapsody"],
    artist: "Queen",
    era: "1970s",
    genre: "Rock",
    firstLetters: "B R",
    difficulty: "extra-hard",
    dayOfWeek: 7,
  },
  {
    id: 122,
    formal: "The Historical Belgian Municipality Renowned As The Geographical Location Of A Decisive Military Engagement In The Year Eighteen Hundred And Fifteen",
    answer: "Waterloo",
    accepted: ["waterloo"],
    artist: "ABBA",
    era: "1970s",
    genre: "Pop",
    firstLetters: "W",
    difficulty: "extra-hard",
    dayOfWeek: 7,
  },
  // Replaced duplicate "Somebody That I Used to Know" (already in daily puzzles as ID 75)
  {
    id: 123,
    formal: "Hypothetical Conditional Scenario In Which The Speaker Were To Declare A Comprehensive Absence Of Emotional Concern Regarding The Prevailing Circumstances",
    answer: "I Don't Care",
    accepted: ["i dont care", "i don't care"],
    artist: "Ed Sheeran & Justin Bieber",
    era: "2010s",
    genre: "Pop",
    firstLetters: "I D C",
    difficulty: "extra-hard",
    dayOfWeek: 7,
  },
  {
    id: 124,
    formal: "An Internationally Standardised Emergency Distress Signal Transmitted Via The Established Morse Code Protocol Of Three Short, Three Long, And Three Short Signals",
    answer: "SOS",
    accepted: ["sos"],
    artist: "ABBA",
    era: "1970s",
    genre: "Pop",
    firstLetters: "S",
    difficulty: "extra-hard",
    dayOfWeek: 7,
  },
  // Replaced duplicate "Superstition" (already in daily puzzles as ID 118)
  {
    id: 125,
    formal: "A Comprehensive Instrumental And Vocal Arrangement Performed During The Nocturnal Hours Immediately Preceding The Commencement Of A Designated Period Of Extended Festivity",
    answer: "New Year's Day",
    accepted: ["new years day", "new year's day"],
    artist: "U2",
    era: "1980s",
    genre: "Rock",
    firstLetters: "N Y D",
    difficulty: "extra-hard",
    dayOfWeek: 7,
  },
];

// ─── Daily puzzles ────────────────────────────────────────────────────────────
export const puzzles: Puzzle[] = [
  // ══════════════════════════════════════════════════════════════════════════════
  // EASY PUZZLES (Monday/Tuesday material)
  // ══════════════════════════════════════════════════════════════════════════════

  // FIXED: Added "It's" mapping, removed lyrics context.
  {
    id: 1,
    formal: "Official Atmospheric Report Confirming That Adult Male Individuals Are Presently Descending From Elevated Atmospheric Regions",
    answer: "It's Raining Men",
    accepted: ["its raining men", "it's raining men", "raining men"],
    artist: "The Weather Girls",
    era: "1980s",
    genre: "Disco / Pop",
    firstLetters: "I R M",
    difficulty: "easy",
    dayOfWeek: 1,
  },
  // FIXED: Removed lyrics interpretation ("emotional liberation"). Now maps title words directly.
  {
    id: 2,
    formal: "Declaration Of Altered Circumstances Commencing From The Temporal Point Of The Recipient's Protracted Absence",
    answer: "Since U Been Gone",
    accepted: ["since u been gone", "since you been gone", "since you've been gone"],
    artist: "Kelly Clarkson",
    era: "2000s",
    genre: "Pop Rock",
    firstLetters: "S U B G",
    difficulty: "easy",
    dayOfWeek: 1,
  },
  // FIXED: Removed "bearded gift-distributing" (thematic). Now translates title words directly.
  {
    id: 4,
    formal: "Official Advance Report Confirming That The Rotund Elderly Gentleman Of Generous Disposition Is Currently Undertaking Directional Movement Toward Your Municipal Settlement",
    answer: "Santa Claus Is Comin' To Town",
    accepted: ["santa claus is coming to town", "santa claus is comin to town"],
    artist: "Various",
    era: "1930s",
    genre: "Christmas / Pop",
    firstLetters: "S C I C T T",
    difficulty: "easy",
    dayOfWeek: 1,
  },
  // FIXED: Removed "uninhibited recreational enjoyment" (lyrics). Title words only.
  {
    id: 6,
    formal: "Emphatic Prohibition Against The Cessation Of The Speaker's Current Activities At This Present Temporal Juncture",
    answer: "Don't Stop Me Now",
    accepted: ["dont stop me now", "don't stop me now"],
    artist: "Queen",
    era: "1970s",
    genre: "Rock",
    firstLetters: "D S M N",
    difficulty: "easy",
    dayOfWeek: 1,
  },
  // FIXED: Tightened to title words only.
  {
    id: 7,
    formal: "Exclamatory Attestation Regarding The Exceptional Quality Of This Global Territorial Expanse",
    answer: "What a Wonderful World",
    accepted: ["what a wonderful world"],
    artist: "Louis Armstrong",
    era: "1960s",
    genre: "Jazz / Pop",
    firstLetters: "W W W",
    difficulty: "easy",
    dayOfWeek: 1,
  },
  // FIXED: Previously translated lyrics (clap along). Now just the title word.
  {
    id: 8,
    formal: "A State Of Pronounced Emotional Contentment And Psychological Satisfaction",
    answer: "Happy",
    accepted: ["happy"],
    artist: "Pharrell Williams",
    era: "2010s",
    genre: "Pop / Soul",
    firstLetters: "H",
    difficulty: "easy",
    dayOfWeek: 1,
  },
  {
    id: 9,
    formal: "Hesitant Solicitation For The Recipient To Make Telephone Contact With The Speaker, Subject To Their Willingness To Do So",
    answer: "Call Me Maybe",
    accepted: ["call me maybe"],
    artist: "Carly Rae Jepsen",
    era: "2010s",
    genre: "Pop",
    firstLetters: "C M M",
    difficulty: "easy",
    dayOfWeek: 2,
  },
  // FIXED: Removed lyrics ("negative external criticism"). Title words only.
  {
    id: 10,
    formal: "Directive To Vigorously Displace An Unspecified Encumbrance Through Rapid Lateral Physical Motion",
    answer: "Shake It Off",
    accepted: ["shake it off"],
    artist: "Taylor Swift",
    era: "2010s",
    genre: "Pop",
    firstLetters: "S I O",
    difficulty: "easy",
    dayOfWeek: 2,
  },
  // FIXED: Removed "dissolution of romantic partnership" (lyrics).
  {
    id: 11,
    formal: "First-Person Declaration Of Continued Biological And Emotional Endurance Into The Foreseeable Future",
    answer: "I Will Survive",
    accepted: ["i will survive"],
    artist: "Gloria Gaynor",
    era: "1970s",
    genre: "Disco",
    firstLetters: "I W S",
    difficulty: "easy",
    dayOfWeek: 2,
  },
  // FIXED: Removed "long period of cold and darkness" (lyrics).
  {
    id: 14,
    formal: "Notification Of The Imminent Arrival Of The Primary Source Of Solar Illumination At This Present Location",
    answer: "Here Comes The Sun",
    accepted: ["here comes the sun"],
    artist: "The Beatles",
    era: "1960s",
    genre: "Rock / Pop",
    firstLetters: "H C S",
    difficulty: "easy",
    dayOfWeek: 2,
  },
  // FIXED: Translated only the title word "Umbrella".
  {
    id: 16,
    formal: "A Portable Collapsible Canopy Designed For Personal Protection Against Atmospheric Precipitation",
    answer: "Umbrella",
    accepted: ["umbrella"],
    artist: "Rihanna",
    era: "2000s",
    genre: "R&B / Pop",
    firstLetters: "U",
    difficulty: "easy",
    dayOfWeek: 1,
  },
  // FIXED: Removed lyrics context from "Never Gonna Give You Up".
  {
    id: 18,
    formal: "Categorical Declaration Of Permanent Refusal To Relinquish Possession Of The Addressed Individual At Any Point In The Future",
    answer: "Never Gonna Give You Up",
    accepted: ["never gonna give you up", "never going to give you up"],
    artist: "Rick Astley",
    era: "1980s",
    genre: "Pop",
    firstLetters: "N G G Y U",
    difficulty: "easy",
    dayOfWeek: 1,
  },
  {
    id: 19,
    formal: "Affirmative Declaration Of Sustained Romantic Devotion To Be Maintained In Perpetuity Toward The Addressed Individual",
    answer: "I Will Always Love You",
    accepted: ["i will always love you", "i'll always love you"],
    artist: "Whitney Houston",
    era: "1990s",
    genre: "R&B / Pop",
    firstLetters: "I W A L Y",
    difficulty: "easy",
    dayOfWeek: 2,
  },
  // FIXED: Removed "festive winter season" (lyrics).
  {
    id: 21,
    formal: "Small Metallic Resonating Instruments Producing A Characteristic Tinkling Percussive Sound",
    answer: "Jingle Bells",
    accepted: ["jingle bells"],
    artist: "Traditional",
    era: "1800s",
    genre: "Christmas / Traditional",
    firstLetters: "J B",
    difficulty: "easy",
    dayOfWeek: 1,
  },
  {
    id: 27,
    formal: "Directive To Release, Relinquish, And Permit The Unspecified Matter To Proceed Without Further Intervention",
    answer: "Let It Go",
    accepted: ["let it go"],
    artist: "Idina Menzel",
    era: "2010s",
    genre: "Soundtrack / Pop",
    firstLetters: "L I G",
    difficulty: "easy",
    dayOfWeek: 2,
  },
  // FIXED: Removed lyrics references ("romantic joy").
  {
    id: 43,
    formal: "Bipedal Ambulatory Transit Conducted Atop Concentrated Solar Illumination",
    answer: "Walking On Sunshine",
    accepted: ["walking on sunshine"],
    artist: "Katrina And The Waves",
    era: "1980s",
    genre: "Pop / Rock",
    firstLetters: "W O S",
    difficulty: "easy",
    dayOfWeek: 1,
  },
  // FIXED: Removed lyrics ("glittering desert gambling city").
  {
    id: 44,
    formal: "Enthusiastic Endorsement Of The Continued Prosperous Existence Of The Principal Municipality Of The State Of Nevada",
    answer: "Viva Las Vegas",
    accepted: ["viva las vegas"],
    artist: "Elvis Presley",
    era: "1960s",
    genre: "Pop / Rock",
    firstLetters: "V L V",
    difficulty: "easy",
    dayOfWeek: 2,
  },
  // FIXED: Removed lyrics ("romantic betrayal, grief").
  {
    id: 45,
    formal: "Continuous Rotational Movement Conducted Within The Profoundest Subaqueous Depths",
    answer: "Rolling In The Deep",
    accepted: ["rolling in the deep"],
    artist: "Adele",
    era: "2010s",
    genre: "Soul / Pop",
    firstLetters: "R I D",
    difficulty: "easy",
    dayOfWeek: 1,
  },
  // FIXED: Removed "North African Hieroglyphic Art" (over-specific).
  {
    id: 47,
    formal: "Directive To Adopt A Mode Of Bipedal Ambulation Characteristic Of An Ancient Egyptian Individual",
    answer: "Walk Like An Egyptian",
    accepted: ["walk like an egyptian"],
    artist: "The Bangles",
    era: "1980s",
    genre: "Pop / Rock",
    firstLetters: "W L E",
    difficulty: "easy",
    dayOfWeek: 2,
  },
  {
    id: 38,
    formal: "Olfactory Sensation Bearing A Marked Resemblance To The Essence Of Adolescent Rebellious Vitality",
    answer: "Smells Like Teen Spirit",
    accepted: ["smells like teen spirit"],
    artist: "Nirvana",
    era: "1990s",
    genre: "Grunge / Rock",
    firstLetters: "S L T S",
    difficulty: "easy",
    dayOfWeek: 1,
  },
  {
    id: 39,
    formal: "Geographic Inquiry Regarding The Current Whereabouts Of Interpersonal Romantic Affection",
    answer: "Where Is The Love",
    accepted: ["where is the love"],
    artist: "The Black Eyed Peas",
    era: "2000s",
    genre: "Hip-Hop / R&B",
    firstLetters: "W I T L",
    difficulty: "easy",
    dayOfWeek: 2,
  },
  // FIXED: Removed "darkness and fear" (lyrics).
  {
    id: 32,
    formal: "Earnest Entreaty For A Companion To Maintain An Upright Posture In Close Physical Proximity To The Speaker",
    answer: "Stand By Me",
    accepted: ["stand by me"],
    artist: "Ben E. King",
    era: "1960s",
    genre: "Soul / R&B",
    firstLetters: "S B M",
    difficulty: "easy",
    dayOfWeek: 1,
  },
  // FIXED: Removed lyrics context ("hope and faith in better future").
  {
    id: 53,
    formal: "Steadfast Prohibition Against The Cessation Of One's Fundamental Conviction And Belief",
    answer: "Don't Stop Believin'",
    accepted: ["dont stop believin", "don't stop believin", "don't stop believing", "dont stop believing"],
    artist: "Journey",
    era: "1980s",
    genre: "Rock",
    firstLetters: "D S B",
    difficulty: "easy",
    dayOfWeek: 2,
  },
  {
    id: 29,
    formal: "A State Of Romantic Infatuation So Intense As To Have Demonstrably Impaired The Subject's Rational Cognitive Faculties",
    answer: "Crazy In Love",
    accepted: ["crazy in love"],
    artist: "Beyoncé",
    era: "2000s",
    genre: "R&B / Pop",
    firstLetters: "C I L",
    difficulty: "easy",
    dayOfWeek: 1,
  },
  {
    id: 62,
    formal: "Declaration That The Speaker's Cardiac Organ Shall Continue Its Operational Functions Indefinitely Despite The Recipient's Departure",
    answer: "My Heart Will Go On",
    accepted: ["my heart will go on"],
    artist: "Celine Dion",
    era: "1990s",
    genre: "Pop / Ballad",
    firstLetters: "M H W G O",
    difficulty: "easy",
    dayOfWeek: 2,
  },
  // FIXED: Removed "imperfections" (lyrics).
  {
    id: 63,
    formal: "The Complete And Undivided Totality Of The Speaker's Being",
    answer: "All of Me",
    accepted: ["all of me"],
    artist: "John Legend",
    era: "2010s",
    genre: "R&B / Pop",
    firstLetters: "A M",
    difficulty: "easy",
    dayOfWeek: 1,
  },
  {
    id: 55,
    formal: "Official Supplication To The Almighty For The Protection And Preservation Of The Reigning Sovereign",
    answer: "God Save The King",
    accepted: ["god save the king", "god save the queen"],
    artist: "Traditional",
    era: "Various",
    genre: "Anthem / Traditional",
    firstLetters: "G S K",
    difficulty: "easy",
    dayOfWeek: 2,
  },
  {
    id: 59,
    formal: "Traditional Communal Vocalisation Conveying Celebratory Greetings On The Annual Anniversary Of One's Birth",
    answer: "Happy Birthday To You",
    accepted: ["happy birthday to you", "happy birthday"],
    artist: "Traditional",
    era: "1900s",
    genre: "Traditional",
    firstLetters: "H B T Y",
    difficulty: "easy",
    dayOfWeek: 1,
  },
  // FIXED: Removed lyrics context ("emotionally malfunctioning").
  {
    id: 67,
    formal: "Stated Intention To Restore Optimal Functional Capacity To The Addressed Individual",
    answer: "Fix You",
    accepted: ["fix you"],
    artist: "Coldplay",
    era: "2000s",
    genre: "Pop / Rock",
    firstLetters: "F Y",
    difficulty: "easy",
    dayOfWeek: 2,
  },
  // FIXED: Corrected direction of directive.
  {
    id: 68,
    formal: "Directive To Permit A Female Individual To Depart Without Further Impediment Or Restraint",
    answer: "Let Her Go",
    accepted: ["let her go"],
    artist: "Passenger",
    era: "2010s",
    genre: "Folk / Pop",
    firstLetters: "L H G",
    difficulty: "easy",
    dayOfWeek: 1,
  },
  {
    id: 69,
    formal: "An Underwater Naval Vessel Of A Chromatic Yellow Hue",
    answer: "Yellow Submarine",
    accepted: ["yellow submarine"],
    artist: "The Beatles",
    era: "1960s",
    genre: "Rock / Pop",
    firstLetters: "Y S",
    difficulty: "easy",
    dayOfWeek: 2,
  },
  // FIXED: Removed lyrics ("cherished individual").
  {
    id: 66,
    formal: "A Chromatic Classification Occupying The Spectral Position Between Orange And Green On The Visible Electromagnetic Spectrum",
    answer: "Yellow",
    accepted: ["yellow"],
    artist: "Coldplay",
    era: "2000s",
    genre: "Pop / Rock",
    firstLetters: "Y",
    difficulty: "easy",
    dayOfWeek: 1,
  },
  // FIXED: Removed context ("this particular evening").
  {
    id: 57,
    formal: "Earnest Request For The Addressed Individual To Remain In The Continued Company Of The Speaker",
    answer: "Stay With Me",
    accepted: ["stay with me"],
    artist: "Sam Smith",
    era: "2010s",
    genre: "Soul / Pop",
    firstLetters: "S W M",
    difficulty: "easy",
    dayOfWeek: 2,
  },
  // FIXED: Removed "periods of personal adversity" (lyrics).
  {
    id: 36,
    formal: "Sincere Invitation To Utilise The Speaker As A Physical Support Structure Via Lateral Gravitational Redistribution",
    answer: "Lean on Me",
    accepted: ["lean on me"],
    artist: "Bill Withers",
    era: "1970s",
    genre: "Soul / R&B",
    firstLetters: "L M",
    difficulty: "easy",
    dayOfWeek: 1,
  },

  // NEW easy puzzles
  {
    id: 126,
    formal: "A Solitary Female Individual Currently Operating Within The Terrestrial Sphere",
    answer: "Single Ladies",
    accepted: ["single ladies", "single ladies put a ring on it"],
    artist: "Beyoncé",
    era: "2000s",
    genre: "R&B / Pop",
    firstLetters: "S L",
    difficulty: "easy",
    dayOfWeek: 1,
  },
  {
    id: 127,
    formal: "Directive To Permit The Situation To Exist In Its Current State",
    answer: "Let It Be",
    accepted: ["let it be"],
    artist: "The Beatles",
    era: "1970s",
    genre: "Rock / Pop",
    firstLetters: "L I B",
    difficulty: "easy",
    dayOfWeek: 2,
  },
  {
    id: 128,
    formal: "Enthusiastic Endorsement Of A Gratifying Emotional State, Accompanied By Vigorous Manual Percussive Activity",
    answer: "If You're Happy and You Know It",
    accepted: ["if youre happy and you know it", "if you're happy and you know it"],
    artist: "Traditional",
    era: "Various",
    genre: "Children's / Traditional",
    firstLetters: "I Y H Y K I",
    difficulty: "easy",
    dayOfWeek: 1,
  },
  {
    id: 129,
    formal: "An Unidentified Individual Possessing The Capacity To Be Romantically Cherished",
    answer: "Somebody to Love",
    accepted: ["somebody to love"],
    artist: "Queen",
    era: "1970s",
    genre: "Rock",
    firstLetters: "S T L",
    difficulty: "easy",
    dayOfWeek: 2,
  },
  {
    id: 130,
    formal: "Salutatory Address Issued During The Diurnal Hours Of Darkness",
    answer: "Hello",
    accepted: ["hello"],
    artist: "Adele",
    era: "2010s",
    genre: "Pop / Soul",
    firstLetters: "H",
    difficulty: "easy",
    dayOfWeek: 1,
  },
  {
    id: 131,
    formal: "A Contented Emotional State Experienced Jointly With Another Individual",
    answer: "Happy Together",
    accepted: ["happy together"],
    artist: "The Turtles",
    era: "1960s",
    genre: "Pop Rock",
    firstLetters: "H T",
    difficulty: "easy",
    dayOfWeek: 2,
  },
  {
    id: 132,
    formal: "Repeated Percussive Contact Applied To A Hinged Entryway Of A Celestial Realm",
    answer: "Knockin' on Heaven's Door",
    accepted: ["knockin on heavens door", "knocking on heavens door", "knockin' on heaven's door"],
    artist: "Bob Dylan / Guns N' Roses",
    era: "1970s",
    genre: "Rock / Folk",
    firstLetters: "K H D",
    difficulty: "easy",
    dayOfWeek: 1,
  },
  {
    id: 133,
    formal: "An Excessively Elevated Core Body Temperature Experienced During The Nocturnal Hours Of A Weekend Evening",
    answer: "Saturday Night Fever",
    accepted: ["saturday night fever"],
    artist: "Bee Gees",
    era: "1970s",
    genre: "Disco",
    firstLetters: "S N F",
    difficulty: "easy",
    dayOfWeek: 2,
  },

  // ══════════════════════════════════════════════════════════════════════════════
  // MEDIUM PUZZLES (Wednesday/Thursday material)
  // ══════════════════════════════════════════════════════════════════════════════

  // FIXED: Removed "ancestral mountain homeland" (lyrics).
  {
    id: 3,
    formal: "Earnest Petition For Return Conveyance To One's Primary Residential Domicile Via Unpaved Rural Thoroughfares",
    answer: "Take Me Home, Country Roads",
    accepted: ["take me home country roads", "country roads", "take me home"],
    artist: "John Denver",
    era: "1970s",
    genre: "Country / Folk",
    firstLetters: "T M H C R",
    difficulty: "medium",
    dayOfWeek: 3,
  },
  // FIXED: Mapped title words directly. "Can't Help Falling in Love".
  {
    id: 5,
    formal: "Acknowledged Inability To Prevent An Involuntary Downward Gravitational Descent Into A State Of Romantic Affection",
    answer: "Can't Help Falling in Love",
    accepted: ["cant help falling in love", "can't help falling in love"],
    artist: "Elvis Presley",
    era: "1960s",
    genre: "Pop / Soul",
    firstLetters: "C H F I L",
    difficulty: "medium",
    dayOfWeek: 3,
  },
  // FIXED: Removed lyrics ("under-resourced individuals sustaining relationship").
  {
    id: 12,
    formal: "Sustained Biological Existence Maintained Exclusively Upon The Foundation Of Devotional Supplication",
    answer: "Living on a Prayer",
    accepted: ["living on a prayer", "livin on a prayer", "livin' on a prayer"],
    artist: "Bon Jovi",
    era: "1980s",
    genre: "Rock",
    firstLetters: "L O A P",
    difficulty: "medium",
    dayOfWeek: 3,
  },
  // FIXED: Mapped title words directly.
  {
    id: 13,
    formal: "Accompanied By A Modest Quantum Of Assistance Provided By One's Personal Associates",
    answer: "With a Little Help from My Friends",
    accepted: ["with a little help from my friends"],
    artist: "The Beatles",
    era: "1960s",
    genre: "Rock / Pop",
    firstLetters: "W L H F M F",
    difficulty: "medium",
    dayOfWeek: 4,
  },
  {
    id: 15,
    formal: "Oscillatory Bodily Movements Performed In The Absence Of Adequate Lighting Conditions",
    answer: "Dancing In The Dark",
    accepted: ["dancing in the dark"],
    artist: "Bruce Springsteen",
    era: "1980s",
    genre: "Rock",
    firstLetters: "D I D",
    difficulty: "medium",
    dayOfWeek: 3,
  },
  {
    id: 17,
    formal: "Mandatory Communal Rhythmic Movement Required Of All Individuals Currently Present At This Immediate Temporal Juncture",
    answer: "Everybody Dance Now",
    accepted: ["everybody dance now", "gonna make you sweat everybody dance now"],
    artist: "C+C Music Factory",
    era: "1990s",
    genre: "Dance / House",
    firstLetters: "E D N",
    difficulty: "medium",
    dayOfWeek: 4,
  },
  // FIXED: Removed "male individual" and "physical altercation" (lyrics).
  {
    id: 20,
    formal: "Imperative Directive To Expeditiously Remove Oneself From The Present Location",
    answer: "Beat It",
    accepted: ["beat it"],
    artist: "Michael Jackson",
    era: "1980s",
    genre: "Pop / Rock",
    firstLetters: "B I",
    difficulty: "medium",
    dayOfWeek: 3,
  },
  // FIXED: Removed "freedom" (lyrics).
  {
    id: 22,
    formal: "Having Entered Biological Existence With The Predetermined Purpose Of Engaging In Accelerated Bipedal Locomotion",
    answer: "Born To Run",
    accepted: ["born to run"],
    artist: "Bruce Springsteen",
    era: "1970s",
    genre: "Rock",
    firstLetters: "B T R",
    difficulty: "medium",
    dayOfWeek: 4,
  },
  // FIXED: Removed "lingering memory of departed partner" (lyrics).
  {
    id: 23,
    formal: "An Unspecified Individual Bearing A Marked Resemblance To The Addressed Party",
    answer: "Someone Like You",
    accepted: ["someone like you"],
    artist: "Adele",
    era: "2010s",
    genre: "Pop / Soul",
    firstLetters: "S L Y",
    difficulty: "medium",
    dayOfWeek: 3,
  },
  // FIXED: Removed "seventeen on Friday evening" (lyrics).
  {
    id: 24,
    formal: "Female Sovereign Distinguished By Exceptional Proficiency In Rhythmic Physical Movement",
    answer: "Dancing Queen",
    accepted: ["dancing queen"],
    artist: "ABBA",
    era: "1970s",
    genre: "Pop / Disco",
    firstLetters: "D Q",
    difficulty: "medium",
    dayOfWeek: 4,
  },
  // FIXED: Removed "equine transportation" (lyrics).
  {
    id: 25,
    formal: "An Antiquated Municipal Thoroughfare Of Considerable Historical Duration",
    answer: "Old Town Road",
    accepted: ["old town road"],
    artist: "Lil Nas X",
    era: "2010s",
    genre: "Country Trap / Hip-Hop",
    firstLetters: "O T R",
    difficulty: "medium",
    dayOfWeek: 3,
  },
  // FIXED: Mapped "Rock Around The Clock" directly.
  {
    id: 28,
    formal: "Vigorous Oscillatory Physical Activity Conducted Circumferentially Around The Entirety Of A Timekeeping Instrument",
    answer: "Rock Around The Clock",
    accepted: ["rock around the clock"],
    artist: "Bill Haley & His Comets",
    era: "1950s",
    genre: "Rock and Roll",
    firstLetters: "R A C",
    difficulty: "medium",
    dayOfWeek: 4,
  },
  // FIXED: Removed "narrow pedestrian infrastructure".
  {
    id: 30,
    formal: "Bipedal Ambulatory Transit Conducted In This Particular Prescribed Manner",
    answer: "Walk This Way",
    accepted: ["walk this way"],
    artist: "Aerosmith / Run DMC",
    era: "1970s",
    genre: "Rock / Hip-Hop",
    firstLetters: "W T W",
    difficulty: "medium",
    dayOfWeek: 3,
  },
  {
    id: 31,
    formal: "Exclamatory Declaration Regarding Impressively Voluminous Spherical Masses Comprised Of Thermal Combustion",
    answer: "Great Balls Of Fire",
    accepted: ["great balls of fire"],
    artist: "Jerry Lee Lewis",
    era: "1950s",
    genre: "Rock and Roll",
    firstLetters: "G B F",
    difficulty: "medium",
    dayOfWeek: 4,
  },
  // NEW ID 33 — replaced old Stairway (moved to bonus 104)
  {
    id: 33,
    formal: "Atmospheric Particulate Matter Carried And Displaced By A Tempestuous Current Of Air",
    answer: "Dust In The Wind",
    accepted: ["dust in the wind"],
    artist: "Kansas",
    era: "1970s",
    genre: "Rock",
    firstLetters: "D I W",
    difficulty: "medium",
    dayOfWeek: 3,
  },
  // FIXED: Removed "adjacent celestial bodies" (lyrics).
  {
    id: 35,
    formal: "Petition For Aerial Conveyance Of The Speaker To The Nearest Natural Lunar Satellite",
    answer: "Fly Me To The Moon",
    accepted: ["fly me to the moon"],
    artist: "Frank Sinatra",
    era: "1960s",
    genre: "Jazz / Pop",
    firstLetters: "F M T M",
    difficulty: "medium",
    dayOfWeek: 4,
  },
  // FIXED: Removed "unwanted emotional memory" (lyrics).
  {
    id: 46,
    formal: "Notification Of The Recurring Arrival Of Atmospheric Precipitation Once More At This Location",
    answer: "Here Comes The Rain Again",
    accepted: ["here comes the rain again"],
    artist: "Eurythmics",
    era: "1980s",
    genre: "Synth-Pop",
    firstLetters: "H C R A",
    difficulty: "medium",
    dayOfWeek: 3,
  },
  // FIXED: Removed "following termination of relationship" (lyrics).
  {
    id: 48,
    formal: "Recently Promulgated Regulatory Guidelines Of An Unprecedented Nature",
    answer: "New Rules",
    accepted: ["new rules"],
    artist: "Dua Lipa",
    era: "2010s",
    genre: "Pop",
    firstLetters: "N R",
    difficulty: "medium",
    dayOfWeek: 4,
  },
  // FIXED: Removed "aspirational longing" (lyrics).
  {
    id: 49,
    formal: "The Sequential Numerical Enumeration Of Luminous Celestial Bodies Visible In The Nocturnal Firmament",
    answer: "Counting Stars",
    accepted: ["counting stars"],
    artist: "OneRepublic",
    era: "2010s",
    genre: "Pop / Rock",
    firstLetters: "C S",
    difficulty: "medium",
    dayOfWeek: 3,
  },
  {
    id: 50,
    formal: "Persistent Imperative To Maintain Continuous Forward Momentum Regardless Of All External Impediments",
    answer: "Keep On Movin'",
    accepted: ["keep on movin", "keep on moving", "keep on movin'"],
    artist: "Soul II Soul",
    era: "1980s",
    genre: "R&B / Soul",
    firstLetters: "K O M",
    difficulty: "medium",
    dayOfWeek: 4,
  },
  // FIXED: Removed "warm sunlit west coast state" (lyrics).
  {
    id: 52,
    formal: "Involuntary Nocturnal Cognitive Activity Pertaining To The Jurisdictional Boundaries Of The State Of California",
    answer: "California Dreamin'",
    accepted: ["california dreamin", "california dreaming", "california dreamin'"],
    artist: "The Mamas & The Papas",
    era: "1960s",
    genre: "Folk Rock / Pop",
    firstLetters: "C D",
    difficulty: "medium",
    dayOfWeek: 3,
  },
  // FIXED: Removed "coping mechanism for fear" (lyrics).
  {
    id: 54,
    formal: "The Speaker's Personally Preferred Collection Of Sensory Experiences And Material Objects",
    answer: "My Favorite Things",
    accepted: ["my favorite things", "my favourite things"],
    artist: "Julie Andrews",
    era: "1960s",
    genre: "Soundtrack / Pop",
    firstLetters: "M F T",
    difficulty: "medium",
    dayOfWeek: 4,
  },
  // FIXED: Removed "life's wonders" (lyrics).
  {
    id: 56,
    formal: "A Natural Aqueous Waterway Bearing The Designation Of The Nearest Lunar Satellite",
    answer: "Moon River",
    accepted: ["moon river"],
    artist: "Henry Mancini / Audrey Hepburn",
    era: "1960s",
    genre: "Jazz / Soundtrack",
    firstLetters: "M R",
    difficulty: "medium",
    dayOfWeek: 3,
  },
  // FIXED: Removed "regardless of distance" (lyrics).
  {
    id: 58,
    formal: "Irrespective Of Any And All Circumstances Or Conditions Whatsoever",
    answer: "No Matter What",
    accepted: ["no matter what"],
    artist: "Boyzone",
    era: "1990s",
    genre: "Pop",
    firstLetters: "N M W",
    difficulty: "medium",
    dayOfWeek: 4,
  },
  // FIXED: Removed "royal authority ordered" and "local populace" (lyrics).
  {
    id: 60,
    formal: "Vigorous Oscillatory Disruption Of A Fortified North African Citadel",
    answer: "Rock The Casbah",
    accepted: ["rock the casbah"],
    artist: "The Clash",
    era: "1980s",
    genre: "Punk / Rock",
    firstLetters: "R C",
    difficulty: "medium",
    dayOfWeek: 3,
  },
  {
    id: 65,
    formal: "A State Of Romantic Intoxication So Extreme That Normal Rational Faculties Have Been Entirely Compromised",
    answer: "Drunk In Love",
    accepted: ["drunk in love"],
    artist: "Beyoncé",
    era: "2010s",
    genre: "R&B / Pop",
    firstLetters: "D I L",
    difficulty: "medium",
    dayOfWeek: 4,
  },
  // FIXED: Removed "enduring romantic commitment" (lyrics).
  {
    id: 71,
    formal: "The Practice Of Externalising Internal Cognitive Deliberations In An Audible Vocal Manner",
    answer: "Thinking Out Loud",
    accepted: ["thinking out loud"],
    artist: "Ed Sheeran",
    era: "2010s",
    genre: "Pop / Soul",
    firstLetters: "T O L",
    difficulty: "medium",
    dayOfWeek: 3,
  },
  // FIXED: Title word only.
  {
    id: 72,
    formal: "A Region Of Notably Insufficient Vertical Depth Below The Surface Level",
    answer: "Shallow",
    accepted: ["shallow"],
    artist: "Lady Gaga & Bradley Cooper",
    era: "2010s",
    genre: "Pop / Country",
    firstLetters: "S",
    difficulty: "medium",
    dayOfWeek: 4,
  },
  // FIXED: Removed "personal difficulty" (lyrics).
  {
    id: 73,
    formal: "Celestial Winged Intermediary Beings Of A Benevolent And Supernatural Disposition",
    answer: "Angels",
    accepted: ["angels"],
    artist: "Robbie Williams",
    era: "1990s",
    genre: "Pop",
    firstLetters: "A",
    difficulty: "medium",
    dayOfWeek: 3,
  },
  {
    id: 74,
    formal: "A Prominent Urban Thoroughfare Lined With The Remnants Of Failed Aspirations And Unrealised Ambitions",
    answer: "Boulevard of Broken Dreams",
    accepted: ["boulevard of broken dreams"],
    artist: "Green Day",
    era: "2000s",
    genre: "Punk Rock",
    firstLetters: "B B D",
    difficulty: "medium",
    dayOfWeek: 4,
  },
  // FIXED: Removed "elevated terrain" abstraction.
  {
    id: 41,
    formal: "Terrain Situated At A Geographically Superior And Elevated Vertical Position",
    answer: "Higher Ground",
    accepted: ["higher ground"],
    artist: "Stevie Wonder",
    era: "1970s",
    genre: "R&B / Soul",
    firstLetters: "H G",
    difficulty: "medium",
    dayOfWeek: 3,
  },

  // NEW medium puzzles
  {
    id: 134,
    formal: "A Nocturnal Avian Creature Of The Corvidae Family, Vocalising Its Characteristic Melodic Composition",
    answer: "Blackbird",
    accepted: ["blackbird"],
    artist: "The Beatles",
    era: "1960s",
    genre: "Rock / Folk",
    firstLetters: "B",
    difficulty: "medium",
    dayOfWeek: 3,
  },
  {
    id: 135,
    formal: "Rhythmic Physical Movement Performed In The Company Of Oneself, Without A Partner Or Companion",
    answer: "Dancing On My Own",
    accepted: ["dancing on my own"],
    artist: "Robyn",
    era: "2010s",
    genre: "Electropop",
    firstLetters: "D O M O",
    difficulty: "medium",
    dayOfWeek: 4,
  },
  {
    id: 136,
    formal: "A Precipitation Of Violet-Hued Atmospheric Moisture",
    answer: "Purple Rain",
    accepted: ["purple rain"],
    artist: "Prince",
    era: "1980s",
    genre: "Pop / Rock",
    firstLetters: "P R",
    difficulty: "medium",
    dayOfWeek: 3,
  },
  {
    id: 137,
    formal: "A Nocturnal Period Of Exceptional Quality Designated For Commendable Experiences",
    answer: "Good Times",
    accepted: ["good times"],
    artist: "Chic",
    era: "1970s",
    genre: "Disco / Funk",
    firstLetters: "G T",
    difficulty: "medium",
    dayOfWeek: 4,
  },
  {
    id: 138,
    formal: "Affectionate Address To An Agreeable Juvenile Offspring Belonging To The Speaker",
    answer: "Sweet Child O' Mine",
    accepted: ["sweet child o mine", "sweet child of mine", "sweet child o' mine"],
    artist: "Guns N' Roses",
    era: "1980s",
    genre: "Rock",
    firstLetters: "S C M",
    difficulty: "medium",
    dayOfWeek: 3,
  },
  {
    id: 139,
    formal: "Atmospheric Precipitation Occurring During The Penultimate Calendar Month Of The Annual Cycle",
    answer: "November Rain",
    accepted: ["november rain"],
    artist: "Guns N' Roses",
    era: "1990s",
    genre: "Rock / Ballad",
    firstLetters: "N R",
    difficulty: "medium",
    dayOfWeek: 4,
  },
  {
    id: 140,
    formal: "Formal Salutation Extended To Individuals Newly Arrived In A Dense Tropical Vegetation Zone",
    answer: "Welcome to the Jungle",
    accepted: ["welcome to the jungle"],
    artist: "Guns N' Roses",
    era: "1980s",
    genre: "Hard Rock",
    firstLetters: "W J",
    difficulty: "medium",
    dayOfWeek: 3,
  },
  {
    id: 141,
    formal: "A Municipal Settlement Of Unparalleled Idyllic Perfection And Utopian Character",
    answer: "Paradise City",
    accepted: ["paradise city"],
    artist: "Guns N' Roses",
    era: "1980s",
    genre: "Hard Rock",
    firstLetters: "P C",
    difficulty: "medium",
    dayOfWeek: 4,
  },
  {
    id: 142,
    formal: "Terminal Sequential Numerical Reduction Preceding An Event Of Great Collective Consequence",
    answer: "The Final Countdown",
    accepted: ["the final countdown", "final countdown"],
    artist: "Europe",
    era: "1980s",
    genre: "Hard Rock",
    firstLetters: "F C",
    difficulty: "medium",
    dayOfWeek: 3,
  },
  {
    id: 143,
    formal: "Collective First-Person Declaration Of Membership In The Category Of Supreme Competitive Victors",
    answer: "We Are the Champions",
    accepted: ["we are the champions"],
    artist: "Queen",
    era: "1970s",
    genre: "Rock",
    firstLetters: "W A C",
    difficulty: "medium",
    dayOfWeek: 4,
  },
  {
    id: 144,
    formal: "Imperative Solicitation For The Addressed Individual To Accept And Assume Responsibility For The Speaker",
    answer: "Take On Me",
    accepted: ["take on me"],
    artist: "a-ha",
    era: "1980s",
    genre: "Synth-Pop",
    firstLetters: "T O M",
    difficulty: "medium",
    dayOfWeek: 3,
  },
  {
    id: 145,
    formal: "Exclamatory Invocation Of One's Maternal Parent Conveying Astonishment Or Dismay",
    answer: "Mamma Mia",
    accepted: ["mamma mia", "mama mia"],
    artist: "ABBA",
    era: "1970s",
    genre: "Pop",
    firstLetters: "M M",
    difficulty: "medium",
    dayOfWeek: 4,
  },
  {
    id: 146,
    formal: "Regulatory Principle Stipulating That The Victorious Party In A Competition Acquires Exclusive Entitlement To All Available Resources",
    answer: "The Winner Takes It All",
    accepted: ["the winner takes it all", "winner takes it all"],
    artist: "ABBA",
    era: "1980s",
    genre: "Pop",
    firstLetters: "W T I A",
    difficulty: "medium",
    dayOfWeek: 3,
  },
  {
    id: 147,
    formal: "Directive For The Convergence Of Multiple Parties Into A State Of Collective Proximity And Unity",
    answer: "Come Together",
    accepted: ["come together"],
    artist: "The Beatles",
    era: "1960s",
    genre: "Rock",
    firstLetters: "C T",
    difficulty: "medium",
    dayOfWeek: 4,
  },

  // ══════════════════════════════════════════════════════════════════════════════
  // HARD PUZZLES (Friday/Saturday material)
  // ══════════════════════════════════════════════════════════════════════════════

  // FIXED: Removed "lachrymatory expulsion of cardiac organ" over-interpretation.
  {
    id: 37,
    formal: "Regulatory Prohibition Against The Continued Lachrymatory Expression Originating From One's Primary Cardiac Organ In An Outward Direction",
    answer: "Stop Crying Your Heart Out",
    accepted: ["stop crying your heart out"],
    artist: "Oasis",
    era: "2000s",
    genre: "Rock / Britpop",
    firstLetters: "S C Y H O",
    difficulty: "hard",
    dayOfWeek: 5,
  },
  // FIXED: Removed "instinct-driven romantic pursuit" (lyrics).
  {
    id: 40,
    formal: "Experiencing Acute Nutritional Deprivation In A Manner Resembling A Predatory Canine Of The Genus Canis Lupus",
    answer: "Hungry Like the Wolf",
    accepted: ["hungry like the wolf"],
    artist: "Duran Duran",
    era: "1980s",
    genre: "New Wave / Pop",
    firstLetters: "H L W",
    difficulty: "hard",
    dayOfWeek: 5,
  },
  // FIXED: Title word only.
  {
    id: 42,
    formal: "An Instance Of Bilateral Labial Contact Between Two Individuals As A Gesture Of Interpersonal Affection",
    answer: "Kiss",
    accepted: ["kiss"],
    artist: "Prince",
    era: "1980s",
    genre: "Funk / Pop",
    firstLetters: "K",
    difficulty: "hard",
    dayOfWeek: 6,
  },
  // ★ DAY 4 (Fri) — First hard puzzle of the week. Multi-word mega-hit with a satisfying decode.
  {
    id: 79,
    formal: "The External Physical Configuration And Anatomical Contours Belonging To The Addressed Individual",
    answer: "Shape of You",
    accepted: ["shape of you"],
    artist: "Ed Sheeran",
    era: "2010s",
    genre: "Pop",
    firstLetters: "S Y",
    difficulty: "hard",
    dayOfWeek: 5,
  },
  // ★ DAY 5 (Sat) — Iconic recent hit, great "aha" moment.
  {
    id: 78,
    formal: "Sources Of Photonic Illumination Of Such Intensity As To Cause Temporary Impairment Of Visual Perception",
    answer: "Blinding Lights",
    accepted: ["blinding lights"],
    artist: "The Weeknd",
    era: "2010s",
    genre: "Synth-Pop",
    firstLetters: "B L",
    difficulty: "hard",
    dayOfWeek: 6,
  },
  // ★ DAY 6 (Sun) — Classic rock icon, multi-word, challenging but rewarding.
  {
    id: 164,
    formal: "An Additional Rectangular Construction Unit Embedded Within A Vertical Structural Partition",
    answer: "Another Brick in the Wall",
    accepted: ["another brick in the wall"],
    artist: "Pink Floyd",
    era: "1970s",
    genre: "Progressive Rock",
    firstLetters: "A B W",
    difficulty: "hard",
    dayOfWeek: 5,
  },
  // (moved from earlier position)
  {
    id: 76,
    formal: "A Substance Or Condition Exhibiting Properties Demonstrably Deleterious To Biological Organisms Upon Exposure",
    answer: "Toxic",
    accepted: ["toxic"],
    artist: "Britney Spears",
    era: "2000s",
    genre: "Pop",
    firstLetters: "T",
    difficulty: "hard",
    dayOfWeek: 5,
  },
  {
    id: 77,
    formal: "A Romantic Interpersonal Attachment Of Demonstrably Inferior Quality And Detrimental Character",
    answer: "Bad Romance",
    accepted: ["bad romance"],
    artist: "Lady Gaga",
    era: "2000s",
    genre: "Pop / Electronic",
    firstLetters: "B R",
    difficulty: "hard",
    dayOfWeek: 6,
  },
  // FIXED: Previously ID 75, now mapped more directly.
  {
    id: 75,
    formal: "An Unspecified Individual With Whom The Speaker Previously Maintained A State Of Personal Acquaintance",
    answer: "Somebody That I Used to Know",
    accepted: ["somebody that i used to know"],
    artist: "Gotye ft. Kimbra",
    era: "2010s",
    genre: "Indie Pop",
    firstLetters: "S T I U K",
    difficulty: "hard",
    dayOfWeek: 5,
  },
  // FIXED: Title word only.
  {
    id: 64,
    formal: "A Transition Metal Element Of Exceptional Structural Resilience Bearing Atomic Number Twenty-Two On The Periodic Table",
    answer: "Titanium",
    accepted: ["titanium"],
    artist: "David Guetta ft. Sia",
    era: "2010s",
    genre: "Electronic / Pop",
    firstLetters: "T",
    difficulty: "hard",
    dayOfWeek: 6,
  },
  // FIXED: Removed "romantic challenge" (lyrics).
  {
    id: 70,
    formal: "Informal Verbal Declaration Of Priority Entitlement To The Anterior Passenger Position Within A Motor Vehicle",
    answer: "Shotgun",
    accepted: ["shotgun"],
    artist: "George Ezra",
    era: "2010s",
    genre: "Pop",
    firstLetters: "S",
    difficulty: "hard",
    dayOfWeek: 5,
  },
  // FIXED: Removed lyrics references.
  {
    id: 90,
    formal: "Nonsensical Repetitive Exclamations Directed Toward An Audio Broadcast Transmission Medium",
    answer: "Radio Ga Ga",
    accepted: ["radio ga ga", "radio gaga"],
    artist: "Queen",
    era: "1980s",
    genre: "Rock / Synth-Pop",
    firstLetters: "R G G",
    difficulty: "hard",
    dayOfWeek: 6,
  },
  // FIXED: Removed "asserting cultural superiority" (lyrics).
  {
    id: 91,
    formal: "Rhythmically Sophisticated Musical Genre Originating From The Affluent Northern Quarter Of A Metropolitan Area",
    answer: "Uptown Funk",
    accepted: ["uptown funk"],
    artist: "Mark Ronson ft. Bruno Mars",
    era: "2010s",
    genre: "Funk / Pop",
    firstLetters: "U F",
    difficulty: "hard",
    dayOfWeek: 5,
  },
  // FIXED: Title word only.
  {
    id: 92,
    formal: "A Formal Expression Of Remorse And Contrition Tendered Without Qualification",
    answer: "Sorry",
    accepted: ["sorry"],
    artist: "Justin Bieber",
    era: "2010s",
    genre: "Pop",
    firstLetters: "S",
    difficulty: "hard",
    dayOfWeek: 6,
  },
  // FIXED: Removed "unsolicited counsel to a former partner" (lyrics).
  {
    id: 93,
    formal: "Directive To Direct Romantic Affection And Devotion Toward One's Own Person",
    answer: "Love Yourself",
    accepted: ["love yourself"],
    artist: "Justin Bieber",
    era: "2010s",
    genre: "Pop",
    firstLetters: "L Y",
    difficulty: "hard",
    dayOfWeek: 5,
  },
  // FIXED: Removed "interpersonal encounter" (lyrics).
  {
    id: 94,
    formal: "Incremental Directive For The Progressive Reduction Of All Activities To The Minimum Attainable Velocity",
    answer: "Despacito",
    accepted: ["despacito"],
    artist: "Luis Fonsi ft. Daddy Yankee",
    era: "2010s",
    genre: "Latin Pop / Reggaeton",
    firstLetters: "D",
    difficulty: "hard",
    dayOfWeek: 6,
  },
  // FIXED: Removed "former partner" (lyrics).
  {
    id: 95,
    formal: "Interrogative Challenge Regarding Whether The Addressed Individual Retains Any Desire For The Speaker's Continued Companionship",
    answer: "Don't You Want Me",
    accepted: ["dont you want me", "don't you want me"],
    artist: "The Human League",
    era: "1980s",
    genre: "Synth-Pop",
    firstLetters: "D Y W M",
    difficulty: "hard",
    dayOfWeek: 5,
  },
  // FIXED: Removed "romantic overtures" (lyrics).
  {
    id: 96,
    formal: "Urgent Entreaty Directed At A Female Individual Named Eileen To Engage Enthusiastically And Without Hesitation",
    answer: "Come On Eileen",
    accepted: ["come on eileen"],
    artist: "Dexys Midnight Runners",
    era: "1980s",
    genre: "Pop / Celtic",
    firstLetters: "C E",
    difficulty: "hard",
    dayOfWeek: 6,
  },
  // FIXED: Removed "rather than said acquaintance herself" (lyrics).
  {
    id: 97,
    formal: "The Maternal Parent Of A Female Individual Known By The Given Name Stacy",
    answer: "Stacy's Mom",
    accepted: ["stacys mom", "stacy's mom"],
    artist: "Fountains of Wayne",
    era: "2000s",
    genre: "Power Pop",
    firstLetters: "S M",
    difficulty: "hard",
    dayOfWeek: 5,
  },
  // FIXED: Replaced Fernando (just a name) with different hard song.
  {
    id: 98,
    formal: "Urgent Iterative Demand For The Immediate Provision Of An Unspecified Object, Repeated Thrice For Emphasis",
    answer: "Gimme! Gimme! Gimme!",
    accepted: ["gimme gimme gimme"],
    artist: "ABBA",
    era: "1980s",
    genre: "Pop / Disco",
    firstLetters: "G G G",
    difficulty: "hard",
    dayOfWeek: 6,
  },
  // FIXED: Removed "romantic crisis" (lyrics).
  {
    id: 99,
    formal: "Romantic Affection That Has Been Irreversibly Contaminated By Deleterious External Influences",
    answer: "Tainted Love",
    accepted: ["tainted love"],
    artist: "Soft Cell",
    era: "1980s",
    genre: "Synth-Pop",
    firstLetters: "T L",
    difficulty: "hard",
    dayOfWeek: 5,
  },
  // FIXED: Removed "ordinary daily activities" (lyrics).
  {
    id: 119,
    formal: "Documentation Of A Female Individual's Capacity To Induce Severe Psychological Disturbance In The Speaker",
    answer: "She Drives Me Crazy",
    accepted: ["she drives me crazy"],
    artist: "Fine Young Cannibals",
    era: "1980s",
    genre: "Pop / R&B",
    firstLetters: "S D M C",
    difficulty: "hard",
    dayOfWeek: 6,
  },
  {
    id: 120,
    formal: "Uncontaminated Cognitive Faculty For Generating Novel Mental Constructs That Transcend The Boundaries Of Physical Reality",
    answer: "Pure Imagination",
    accepted: ["pure imagination"],
    artist: "Gene Wilder",
    era: "1970s",
    genre: "Soundtrack / Pop",
    firstLetters: "P I",
    difficulty: "hard",
    dayOfWeek: 5,
  },
  {
    id: 118,
    formal: "An Irrational System Of Belief Predicated Upon Spurious Causal Relationships Between Ritual Behaviours And Subsequent Occurrences",
    answer: "Superstition",
    accepted: ["superstition"],
    artist: "Stevie Wonder",
    era: "1970s",
    genre: "Funk / Soul",
    firstLetters: "S",
    difficulty: "hard",
    dayOfWeek: 6,
  },

  // NEW hard puzzles
  {
    id: 148,
    formal: "A Solitary Residential Unit Within A Multi-Occupancy Structure Located On A Remote Thoroughfare Of Emotional Desolation",
    answer: "Heartbreak Hotel",
    accepted: ["heartbreak hotel"],
    artist: "Elvis Presley",
    era: "1950s",
    genre: "Rock and Roll",
    firstLetters: "H H",
    difficulty: "hard",
    dayOfWeek: 5,
  },
  {
    id: 149,
    formal: "Frozen Crystalline Precipitation, Repeated For Emphasis, Followed By An Informal Designation For A Juvenile Individual",
    answer: "Ice Ice Baby",
    accepted: ["ice ice baby"],
    artist: "Vanilla Ice",
    era: "1990s",
    genre: "Hip-Hop",
    firstLetters: "I I B",
    difficulty: "hard",
    dayOfWeek: 6,
  },
  {
    id: 150,
    formal: "Loosely Fitted Lower Body Garments Of Excessive Circumferential Dimension",
    answer: "Baggy Trousers",
    accepted: ["baggy trousers"],
    artist: "Madness",
    era: "1980s",
    genre: "Ska / Pop",
    firstLetters: "B T",
    difficulty: "hard",
    dayOfWeek: 5,
  },
  {
    id: 151,
    formal: "Juvenile Female Individuals Whose Sole Aspiration Consists Of The Acquisition Of Recreational Enjoyment",
    answer: "Girls Just Want to Have Fun",
    accepted: ["girls just want to have fun", "girls just wanna have fun"],
    artist: "Cyndi Lauper",
    era: "1980s",
    genre: "Pop",
    firstLetters: "G J W H F",
    difficulty: "hard",
    dayOfWeek: 6,
  },
  {
    id: 152,
    formal: "Monetary Remuneration Insufficient To Procure The Intangible Emotional State Of Romantic Affection",
    answer: "Can't Buy Me Love",
    accepted: ["cant buy me love", "can't buy me love"],
    artist: "The Beatles",
    era: "1960s",
    genre: "Rock / Pop",
    firstLetters: "C B M L",
    difficulty: "hard",
    dayOfWeek: 5,
  },
  {
    id: 153,
    formal: "Exuberant Rhythmic Physical Movements Executed Upon The Elevated Surface Of A Structural Covering",
    answer: "Dancing on the Ceiling",
    accepted: ["dancing on the ceiling"],
    artist: "Lionel Richie",
    era: "1980s",
    genre: "Pop / R&B",
    firstLetters: "D O C",
    difficulty: "hard",
    dayOfWeek: 6,
  },
  {
    id: 154,
    formal: "Vocalisation Of A Diminutive Devotional Supplication On Behalf Of The Addressed Individual",
    answer: "Say a Little Prayer",
    accepted: ["say a little prayer", "i say a little prayer", "i say a little prayer for you"],
    artist: "Aretha Franklin",
    era: "1960s",
    genre: "Soul / R&B",
    firstLetters: "S L P",
    difficulty: "hard",
    dayOfWeek: 5,
  },
  {
    id: 155,
    formal: "The Central Commercial And Residential District Of A Municipal Settlement",
    answer: "Downtown",
    accepted: ["downtown"],
    artist: "Petula Clark",
    era: "1960s",
    genre: "Pop",
    firstLetters: "D",
    difficulty: "hard",
    dayOfWeek: 6,
  },
  {
    id: 156,
    formal: "A Recreational Pursuit Involving The Systematic Elimination Of Phantasmagorical Apparitions Via Specialised Audio-Frequency Telecommunications Equipment",
    answer: "Ghostbusters",
    accepted: ["ghostbusters", "who you gonna call ghostbusters"],
    artist: "Ray Parker Jr.",
    era: "1980s",
    genre: "Pop / Soundtrack",
    firstLetters: "G",
    difficulty: "hard",
    dayOfWeek: 5,
  },
  {
    id: 157,
    formal: "Elevation Of One's Transparent Drinking Vessel In A Celebratory Gesture",
    answer: "Raise Your Glass",
    accepted: ["raise your glass"],
    artist: "Pink",
    era: "2010s",
    genre: "Pop Rock",
    firstLetters: "R Y G",
    difficulty: "hard",
    dayOfWeek: 6,
  },
  {
    id: 158,
    formal: "Thermal Combustion Event Occurring Within The Context Of An Interpersonal Meteorological Precipitation Event",
    answer: "Fire and Rain",
    accepted: ["fire and rain"],
    artist: "James Taylor",
    era: "1970s",
    genre: "Folk Rock",
    firstLetters: "F R",
    difficulty: "hard",
    dayOfWeek: 5,
  },
  {
    id: 159,
    formal: "Directive To Apply Forceful Physical Impact Upon The Speaker, Followed By An Affectionate Diminutive And A Request For One Additional Occurrence",
    answer: "Hit Me Baby One More Time",
    accepted: ["hit me baby one more time", "baby one more time"],
    artist: "Britney Spears",
    era: "1990s",
    genre: "Pop",
    firstLetters: "H M B O M T",
    difficulty: "hard",
    dayOfWeek: 6,
  },
  {
    id: 160,
    formal: "An Idyllic Realm Of Unparalleled Bliss And Perpetual Contentment",
    answer: "Paradise",
    accepted: ["paradise"],
    artist: "Coldplay",
    era: "2010s",
    genre: "Pop / Rock",
    firstLetters: "P",
    difficulty: "hard",
    dayOfWeek: 5,
  },
  {
    id: 161,
    formal: "Interrogative Inquiry Regarding The Addressed Individual's Desire To Construct An Anthropomorphic Figure Composed Of Frozen Crystalline Precipitation",
    answer: "Do You Want to Build a Snowman",
    accepted: ["do you want to build a snowman"],
    artist: "Kristen Bell",
    era: "2010s",
    genre: "Soundtrack / Pop",
    firstLetters: "D Y W B S",
    difficulty: "hard",
    dayOfWeek: 6,
  },
  {
    id: 162,
    formal: "An Extended Serpentine Thoroughfare Characterised By Sinuous Curvatures And Progressive Directional Alterations",
    answer: "The Long and Winding Road",
    accepted: ["the long and winding road", "long and winding road"],
    artist: "The Beatles",
    era: "1970s",
    genre: "Rock / Pop",
    firstLetters: "L W R",
    difficulty: "hard",
    dayOfWeek: 5,
  },
  {
    id: 163,
    formal: "An Adult Male Individual Composed Entirely Of A Dense Ferrous Metallic Alloy",
    answer: "Iron Man",
    accepted: ["iron man"],
    artist: "Black Sabbath",
    era: "1970s",
    genre: "Heavy Metal",
    firstLetters: "I M",
    difficulty: "hard",
    dayOfWeek: 6,
  },
  // (Another Brick in the Wall moved to week-1 slot above)
  {
    id: 201,
    formal: "A Precipitous Descent Of Emotional Significance Experienced During A Period Of Unconstrained Gravitational Acceleration",
    answer: "Free Fallin'",
    accepted: ["free fallin", "free falling", "free fallin'"],
    artist: "Tom Petty",
    era: "1980s",
    genre: "Rock",
    firstLetters: "F F",
    difficulty: "hard",
    dayOfWeek: 5,
  },
  {
    id: 165,
    formal: "An Incorporeal Metaphysical Essence Situated Within The Elevated Celestial Firmament",
    answer: "Spirit in the Sky",
    accepted: ["spirit in the sky"],
    artist: "Norman Greenbaum",
    era: "1970s",
    genre: "Rock",
    firstLetters: "S S",
    difficulty: "hard",
    dayOfWeek: 6,
  },
  {
    id: 166,
    formal: "A Diminutive Chromatic Crimson Automotive Vehicle Of The Chevrolet Marque",
    answer: "Little Red Corvette",
    accepted: ["little red corvette"],
    artist: "Prince",
    era: "1980s",
    genre: "Pop / Funk",
    firstLetters: "L R C",
    difficulty: "hard",
    dayOfWeek: 5,
  },
  {
    id: 167,
    formal: "A Distance Of Five Hundred Units Of Imperial Linear Measurement",
    answer: "500 Miles",
    accepted: ["500 miles", "five hundred miles", "im gonna be 500 miles"],
    artist: "The Proclaimers",
    era: "1980s",
    genre: "Pop / Folk",
    firstLetters: "5 M",
    difficulty: "hard",
    dayOfWeek: 6,
  },
  {
    id: 168,
    formal: "A Formal Commemorative Observance Of A Significant Occasion Or Achievement",
    answer: "Celebration",
    accepted: ["celebration"],
    artist: "Kool & The Gang",
    era: "1980s",
    genre: "Funk / Disco",
    firstLetters: "C",
    difficulty: "hard",
    dayOfWeek: 5,
  },
  {
    id: 169,
    formal: "A Complete Absence Of Tactile Or Emotional Sensitivity Throughout The Entirety Of One's Being",
    answer: "Numb",
    accepted: ["numb"],
    artist: "Linkin Park",
    era: "2000s",
    genre: "Nu Metal / Rock",
    firstLetters: "N",
    difficulty: "hard",
    dayOfWeek: 6,
  },
  {
    id: 170,
    formal: "Vigorous Oscillatory Motion Applied To The Addressed Individual's Physical Form",
    answer: "Rock Your Body",
    accepted: ["rock your body"],
    artist: "Justin Timberlake",
    era: "2000s",
    genre: "Pop / R&B",
    firstLetters: "R Y B",
    difficulty: "hard",
    dayOfWeek: 5,
  },
  {
    id: 171,
    formal: "A Spherical Demolition Apparatus Designed For The Systematic Destruction Of Structural Edifices",
    answer: "Wrecking Ball",
    accepted: ["wrecking ball"],
    artist: "Miley Cyrus",
    era: "2010s",
    genre: "Pop / Rock",
    firstLetters: "W B",
    difficulty: "hard",
    dayOfWeek: 6,
  },
  {
    id: 172,
    formal: "The Obscured Hemisphere Of The Nearest Natural Lunar Satellite Perpetually Averted From Terrestrial Observation",
    answer: "Dark Side of the Moon",
    accepted: ["dark side of the moon", "the dark side of the moon"],
    artist: "Pink Floyd",
    era: "1970s",
    genre: "Progressive Rock",
    firstLetters: "D S M",
    difficulty: "hard",
    dayOfWeek: 5,
  },
  {
    id: 173,
    formal: "Nocturnal Cognitive Activity Experienced During The Diurnal Hours As An Involuntary Reverie",
    answer: "Daydream Believer",
    accepted: ["daydream believer"],
    artist: "The Monkees",
    era: "1960s",
    genre: "Pop / Rock",
    firstLetters: "D B",
    difficulty: "hard",
    dayOfWeek: 6,
  },
  {
    id: 174,
    formal: "A Female Sovereign Exercising Dominion Over The Entirety Of The Nocturnal Temporal Period",
    answer: "Queen of the Night",
    accepted: ["queen of the night"],
    artist: "Whitney Houston",
    era: "1990s",
    genre: "Pop / R&B",
    firstLetters: "Q N",
    difficulty: "hard",
    dayOfWeek: 5,
  },
  {
    id: 175,
    formal: "Emphatic Prohibition Against The Cessation Of Organised Melodic And Rhythmic Sound Production",
    answer: "Don't Stop the Music",
    accepted: ["dont stop the music", "don't stop the music"],
    artist: "Rihanna",
    era: "2000s",
    genre: "Pop / Dance",
    firstLetters: "D S M",
    difficulty: "hard",
    dayOfWeek: 6,
  },

  // ══════════════════════════════════════════════════════════════════════════════
  // ADDITIONAL PUZZLES TO REACH 200
  // ══════════════════════════════════════════════════════════════════════════════

  // Easy additions
  {
    id: 176,
    formal: "An Expression Of Positive Regard Directed Toward The Act Of Vigorous Oscillatory Physical Activity",
    answer: "I Love Rock 'n' Roll",
    accepted: ["i love rock n roll", "i love rock and roll", "i love rock 'n' roll"],
    artist: "Joan Jett",
    era: "1980s",
    genre: "Rock",
    firstLetters: "I L R R",
    difficulty: "easy",
    dayOfWeek: 1,
  },
  {
    id: 177,
    formal: "Diurnal Illumination Penetrating Through A Translucent Atmospheric Moisture Formation",
    answer: "Sun Is Shining",
    accepted: ["sun is shining"],
    artist: "Bob Marley",
    era: "1970s",
    genre: "Reggae",
    firstLetters: "S I S",
    difficulty: "easy",
    dayOfWeek: 2,
  },
  {
    id: 178,
    formal: "A Fundamental Interpersonal Entitlement To Dignified And Courteous Treatment From All Parties",
    answer: "Respect",
    accepted: ["respect"],
    artist: "Aretha Franklin",
    era: "1960s",
    genre: "Soul / R&B",
    firstLetters: "R",
    difficulty: "easy",
    dayOfWeek: 1,
  },
  {
    id: 179,
    formal: "A Comprehensive Aggregation Of The Speaker's Romantic Affection And Devotional Sentiments",
    answer: "All You Need Is Love",
    accepted: ["all you need is love"],
    artist: "The Beatles",
    era: "1960s",
    genre: "Rock / Pop",
    firstLetters: "A Y N I L",
    difficulty: "easy",
    dayOfWeek: 2,
  },
  {
    id: 180,
    formal: "A Sentiment Of Profound Well-Being And Emotional Uplift, Expressed In The Present Temporal State",
    answer: "Feeling Good",
    accepted: ["feeling good", "feelin good"],
    artist: "Nina Simone",
    era: "1960s",
    genre: "Jazz / Soul",
    firstLetters: "F G",
    difficulty: "easy",
    dayOfWeek: 1,
  },

  // Medium additions
  {
    id: 181,
    formal: "Accelerated Bipedal Locomotion Directed Toward The Observed Global Territorial Expanse",
    answer: "Running Up That Hill",
    accepted: ["running up that hill"],
    artist: "Kate Bush",
    era: "1980s",
    genre: "Art Pop",
    firstLetters: "R U H",
    difficulty: "medium",
    dayOfWeek: 3,
  },
  {
    id: 182,
    formal: "A Vibratory Disturbance In The Atmospheric Medium Transmitted At Audible Frequencies, Characterised By An Absence Of Vocalisation",
    answer: "The Sound of Silence",
    accepted: ["the sound of silence", "sound of silence"],
    artist: "Simon & Garfunkel",
    era: "1960s",
    genre: "Folk Rock",
    firstLetters: "S S",
    difficulty: "medium",
    dayOfWeek: 4,
  },
  {
    id: 183,
    formal: "A Designated Temporal Occasion Reserved For The Exclusive Enjoyment Of The Speaker And The Addressed Individual",
    answer: "Time of Our Lives",
    accepted: ["time of our lives", "the time of our lives"],
    artist: "Various",
    era: "Various",
    genre: "Pop",
    firstLetters: "T O L",
    difficulty: "medium",
    dayOfWeek: 3,
  },
  {
    id: 184,
    formal: "Chromatic Illumination Of An Emerald Hue Indicating Authorised Continuation Of Forward Movement",
    answer: "Green Light",
    accepted: ["green light"],
    artist: "Lorde",
    era: "2010s",
    genre: "Electropop",
    firstLetters: "G L",
    difficulty: "medium",
    dayOfWeek: 4,
  },
  {
    id: 185,
    formal: "Suspended Existence Maintained Upon The Periphery Of Magnificent Splendour",
    answer: "Living on the Edge",
    accepted: ["living on the edge", "livin on the edge"],
    artist: "Aerosmith",
    era: "1990s",
    genre: "Rock",
    firstLetters: "L O E",
    difficulty: "medium",
    dayOfWeek: 3,
  },
  {
    id: 186,
    formal: "An Epistle Of Affection Composed And Dispatched Through The Established Postal Service Infrastructure",
    answer: "Love Letter",
    accepted: ["love letter", "love letters"],
    artist: "Various",
    era: "1950s",
    genre: "R&B / Pop",
    firstLetters: "L L",
    difficulty: "medium",
    dayOfWeek: 4,
  },
  {
    id: 187,
    formal: "A Demonstrative Exposition Of The Methodology By Which The Collective Accomplishes The Task At Hand",
    answer: "This Is How We Do It",
    accepted: ["this is how we do it"],
    artist: "Montell Jordan",
    era: "1990s",
    genre: "R&B / Hip-Hop",
    firstLetters: "T I H W D I",
    difficulty: "medium",
    dayOfWeek: 3,
  },
  {
    id: 188,
    formal: "A Precious Auriferous Metallic Element Of Considerable Monetary And Aesthetic Value",
    answer: "Gold",
    accepted: ["gold"],
    artist: "Spandau Ballet",
    era: "1980s",
    genre: "Pop / New Romantic",
    firstLetters: "G",
    difficulty: "medium",
    dayOfWeek: 4,
  },
  {
    id: 189,
    formal: "Collective Proposal To Engage In Rhythmic Physical Movement At This Present Juncture",
    answer: "Let's Dance",
    accepted: ["lets dance", "let's dance"],
    artist: "David Bowie",
    era: "1980s",
    genre: "Pop / Rock",
    firstLetters: "L D",
    difficulty: "medium",
    dayOfWeek: 3,
  },

  // Hard additions
  {
    id: 190,
    formal: "A Confectionery Establishment Purveying Assorted Saccharine Preparations To A Diverse Clientele",
    answer: "Candy Shop",
    accepted: ["candy shop"],
    artist: "50 Cent",
    era: "2000s",
    genre: "Hip-Hop",
    firstLetters: "C S",
    difficulty: "hard",
    dayOfWeek: 5,
  },
  {
    id: 191,
    formal: "Enduring Emotional Attachment Characterised By An Interminable Temporal Duration",
    answer: "Endless Love",
    accepted: ["endless love"],
    artist: "Diana Ross & Lionel Richie",
    era: "1980s",
    genre: "R&B / Pop",
    firstLetters: "E L",
    difficulty: "hard",
    dayOfWeek: 6,
  },
  {
    id: 192,
    formal: "A Persistent Nocturnal Cerebral Activity Characterised By Aspirational And Fantastical Content",
    answer: "Dreams",
    accepted: ["dreams"],
    artist: "Fleetwood Mac",
    era: "1970s",
    genre: "Rock",
    firstLetters: "D",
    difficulty: "hard",
    dayOfWeek: 5,
  },
  {
    id: 193,
    formal: "A Fervent Personal Aspiration Maintained Throughout The Nocturnal Hours Of Unconscious Repose",
    answer: "Dream On",
    accepted: ["dream on"],
    artist: "Aerosmith",
    era: "1970s",
    genre: "Rock",
    firstLetters: "D O",
    difficulty: "hard",
    dayOfWeek: 6,
  },
  {
    id: 194,
    formal: "A Structural Passageway Spanning An Aqueous Barrier, Constructed Over Turbulent Hydrological Conditions",
    answer: "Bridge over Troubled Water",
    accepted: ["bridge over troubled water"],
    artist: "Simon & Garfunkel",
    era: "1970s",
    genre: "Folk Rock / Pop",
    firstLetters: "B O T W",
    difficulty: "hard",
    dayOfWeek: 5,
  },
  {
    id: 195,
    formal: "An Adult Male Individual Situated Within The Reflective Glass Surface Of A Looking Apparatus",
    answer: "Man in the Mirror",
    accepted: ["man in the mirror"],
    artist: "Michael Jackson",
    era: "1980s",
    genre: "Pop",
    firstLetters: "M M",
    difficulty: "hard",
    dayOfWeek: 6,
  },
  {
    id: 196,
    formal: "A Comprehensive Nocturnal Musical Event Spanning The Entirety Of The Dark Hours Until Solar Re-Emergence",
    answer: "All Night Long",
    accepted: ["all night long"],
    artist: "Lionel Richie",
    era: "1980s",
    genre: "Pop / R&B",
    firstLetters: "A N L",
    difficulty: "hard",
    dayOfWeek: 5,
  },
  {
    id: 197,
    formal: "A Domesticated Feline Of Pronounced Dermal Pigmentation Resulting In Suboptimal Fortune",
    answer: "Black Cat",
    accepted: ["black cat"],
    artist: "Janet Jackson",
    era: "1990s",
    genre: "Pop / Rock",
    firstLetters: "B C",
    difficulty: "hard",
    dayOfWeek: 6,
  },
  {
    id: 198,
    formal: "Directive To Proceed In A State Of Profound Equanimity And Compose An Inventory Of Significant Determinations",
    answer: "Everybody Hurts",
    accepted: ["everybody hurts"],
    artist: "R.E.M.",
    era: "1990s",
    genre: "Alternative Rock",
    firstLetters: "E H",
    difficulty: "hard",
    dayOfWeek: 5,
  },
  {
    id: 199,
    formal: "A Cylindrical Wax Illumination Device Situated Within A Current Of Atmospheric Turbulence",
    answer: "Candle in the Wind",
    accepted: ["candle in the wind"],
    artist: "Elton John",
    era: "1970s",
    genre: "Pop / Rock",
    firstLetters: "C W",
    difficulty: "hard",
    dayOfWeek: 6,
  },
  {
    id: 200,
    formal: "The Diurnal Period Occurring Subsequent To The Present Twenty-Four Hour Cycle, Perpetually Deferred Beyond Immediate Temporal Access",
    answer: "Tomorrow",
    accepted: ["tomorrow"],
    artist: "Annie (Musical)",
    era: "1970s",
    genre: "Musical / Soundtrack",
    firstLetters: "T",
    difficulty: "hard",
    dayOfWeek: 5,
  },

  // ══════════════════════════════════════════════════════════════════════════════
  // FINAL BATCH — bringing total to 200
  // ══════════════════════════════════════════════════════════════════════════════

  // Easy
  {
    id: 202,
    formal: "An Entreaty For Continued Musical Activity Without Interruption",
    answer: "Play That Funky Music",
    accepted: ["play that funky music", "play that funky music white boy"],
    artist: "Wild Cherry",
    era: "1970s",
    genre: "Funk / Rock",
    firstLetters: "P T F M",
    difficulty: "easy",
    dayOfWeek: 1,
  },
  {
    id: 203,
    formal: "An Adult Male Individual Employed In The Operation Of A Cylindrical Propulsive Aerospace Vehicle",
    answer: "Rocket Man",
    accepted: ["rocket man"],
    artist: "Elton John",
    era: "1970s",
    genre: "Pop / Rock",
    firstLetters: "R M",
    difficulty: "easy",
    dayOfWeek: 2,
  },
  {
    id: 204,
    formal: "Vocal Utterances Produced Without Semantic Content During Nocturnal Musical Performances",
    answer: "La La La",
    accepted: ["la la la"],
    artist: "Naughty Boy ft. Sam Smith",
    era: "2010s",
    genre: "Pop / Electronic",
    firstLetters: "L L L",
    difficulty: "easy",
    dayOfWeek: 1,
  },

  // Medium
  {
    id: 205,
    formal: "An Ongoing Temporal Interval During Which The Speaker's Biological Existence Continues Unabated",
    answer: "Time of My Life",
    accepted: ["time of my life", "the time of my life", "ive had the time of my life"],
    artist: "Bill Medley & Jennifer Warnes",
    era: "1980s",
    genre: "Pop / Soundtrack",
    firstLetters: "T M L",
    difficulty: "medium",
    dayOfWeek: 3,
  },
  {
    id: 206,
    formal: "A Traditional Melodic Composition Concerning The Sustained Emotional Devotion Existing Between Two Individuals",
    answer: "Love Song",
    accepted: ["love song"],
    artist: "The Cure",
    era: "1980s",
    genre: "Alternative Rock",
    firstLetters: "L S",
    difficulty: "medium",
    dayOfWeek: 4,
  },
  {
    id: 208,
    formal: "Admission That The Speaker's Romantic Affection Persists Despite Concerted Efforts To Eliminate Said Sentiment",
    answer: "Still Loving You",
    accepted: ["still loving you"],
    artist: "Scorpions",
    era: "1980s",
    genre: "Rock",
    firstLetters: "S L Y",
    difficulty: "medium",
    dayOfWeek: 4,
  },
  {
    id: 209,
    formal: "A Portable Audio Reproduction Apparatus Of Considerable Volume And Bass Frequency Output",
    answer: "Boombox",
    accepted: ["boombox"],
    artist: "The Lonely Island",
    era: "2000s",
    genre: "Comedy / Hip-Hop",
    firstLetters: "B",
    difficulty: "medium",
    dayOfWeek: 3,
  },

  // Hard
  {
    id: 210,
    formal: "The Particular Methodology Through Which The Speaker Derives Optimal Satisfaction From Romantic Companionship",
    answer: "The Way You Make Me Feel",
    accepted: ["the way you make me feel"],
    artist: "Michael Jackson",
    era: "1980s",
    genre: "Pop",
    firstLetters: "W Y M M F",
    difficulty: "hard",
    dayOfWeek: 5,
  },
  {
    id: 211,
    formal: "A Comprehensive And Unqualified Astronomical Darkening Of The Primary Source Of Solar Illumination",
    answer: "Black Hole Sun",
    accepted: ["black hole sun"],
    artist: "Soundgarden",
    era: "1990s",
    genre: "Grunge / Rock",
    firstLetters: "B H S",
    difficulty: "hard",
    dayOfWeek: 6,
  },
  {
    id: 212,
    formal: "Intense Photonic Emission Resembling That Of A Precious Crystalline Carbon Allotrope Suspended In The Celestial Firmament",
    answer: "Shine On You Crazy Diamond",
    accepted: ["shine on you crazy diamond"],
    artist: "Pink Floyd",
    era: "1970s",
    genre: "Progressive Rock",
    firstLetters: "S O Y C D",
    difficulty: "hard",
    dayOfWeek: 5,
  },
  {
    id: 213,
    formal: "A Projectile Discharged Through The Central Cardiac Organ Of The Addressed Individual",
    answer: "Shot Through the Heart",
    accepted: ["shot through the heart", "you give love a bad name"],
    artist: "Bon Jovi",
    era: "1980s",
    genre: "Rock",
    firstLetters: "S T H",
    difficulty: "hard",
    dayOfWeek: 6,
  },
  {
    id: 214,
    formal: "Geographical Features Characterised By The Vertical Cascading Descent Of Aqueous Volumes Over Precipitous Geological Formations",
    answer: "Waterfalls",
    accepted: ["waterfalls"],
    artist: "TLC",
    era: "1990s",
    genre: "R&B / Pop",
    firstLetters: "W",
    difficulty: "hard",
    dayOfWeek: 5,
  },
  {
    id: 215,
    formal: "Declaration That The Speaker Currently Possesses An Elevated Emotional State And Is Cognisant Of This Condition",
    answer: "I Gotta Feeling",
    accepted: ["i gotta feeling", "i got a feeling", "i've got a feeling"],
    artist: "The Black Eyed Peas",
    era: "2000s",
    genre: "Pop / Dance",
    firstLetters: "I G F",
    difficulty: "hard",
    dayOfWeek: 6,
  },
  {
    id: 216,
    formal: "A Benevolent And Compassionate Celestial Being Assigned To Monitor And Protect A Specific Terrestrial Individual",
    answer: "Guardian Angel",
    accepted: ["guardian angel"],
    artist: "Various",
    era: "Various",
    genre: "R&B / Pop",
    firstLetters: "G A",
    difficulty: "hard",
    dayOfWeek: 5,
  },
  {
    id: 217,
    formal: "Illuminated Photonic Display Devices Suspended Against An Obscured Nocturnal Urban Firmament",
    answer: "City of Stars",
    accepted: ["city of stars"],
    artist: "Ryan Gosling & Emma Stone",
    era: "2010s",
    genre: "Soundtrack / Jazz",
    firstLetters: "C S",
    difficulty: "hard",
    dayOfWeek: 6,
  },
  {
    id: 218,
    formal: "An Individual Of Particularly Smooth And Practised Social Deportment, Identifiable As A Criminal Operative Of Considerable Sophistication",
    answer: "Smooth Criminal",
    accepted: ["smooth criminal"],
    artist: "Michael Jackson",
    era: "1980s",
    genre: "Pop",
    firstLetters: "S C",
    difficulty: "hard",
    dayOfWeek: 5,
  },
];
