export interface Puzzle {
  id: number;
  formal: string;         // The bureaucratic translation shown to the player
  answer: string;         // Primary correct answer (canonical)
  accepted: string[];     // All acceptable answers (fuzzy matched against these)
  artist: string;         // Revealed as hint 3
  era: string;            // e.g. "1980s" — revealed as hint 1
  genre: string;          // e.g. "Pop" — revealed as hint 4
  firstLetters: string;   // e.g. "T M H C R" — revealed as hint 2
  difficulty: 'easy' | 'medium' | 'hard';
}

// ─── Bonus puzzles — extra-hard, one per week ────────────────────────────────
// IDs 101–115 reserved for bonus puzzles
export const bonusPuzzles: Puzzle[] = [
  {
    id: 101,
    formal: "Terms And Conditions Governing Extended Residency At A Hospitality Establishment Of Ambiguous Geographical Provenance, From Which Voluntary Departure Has Been Contractually Rendered Theoretically Impossible",
    answer: "Hotel California",
    accepted: ["hotel california"],
    artist: "Eagles",
    era: "1970s",
    genre: "Rock",
    firstLetters: "H C",
    difficulty: "hard",
  },
  {
    id: 102,
    formal: "Involuntary Cognitive Surveillance Operation Conducted Against A Competing Male Party Presumed To Be Succeeding In The Romantic Pursuit Of The Object Of One's Unrequited Affective Investment",
    answer: "Mr. Brightside",
    accepted: ["mr brightside", "mr. brightside", "mister brightside"],
    artist: "The Killers",
    era: "2000s",
    genre: "Indie Rock",
    firstLetters: "M B",
    difficulty: "hard",
  },
  {
    id: 103,
    formal: "Anticipated Meteorological Precipitation Events In The Sub-Equatorial Continental Mass, Notwithstanding The Continued Psychological Influence Of Prior Interpersonal Romantic History",
    answer: "Africa",
    accepted: ["africa"],
    artist: "Toto",
    era: "1980s",
    genre: "Pop / Rock",
    firstLetters: "A",
    difficulty: "hard",
  },
  {
    id: 104,
    formal: "Formal Regulatory Directive Prohibiting The Practice Of Providing Remunerated Companionship Services During Nocturnal Temporal Hours",
    answer: "Roxanne",
    accepted: ["roxanne"],
    artist: "The Police",
    era: "1970s",
    genre: "Rock / Reggae",
    firstLetters: "R",
    difficulty: "hard",
  },
  {
    id: 105,
    formal: "Declaration That An Unidentified Individual May Constitute The Structural Psychological Barrier Preventing Complete Personal Deterioration And Existential Collapse",
    answer: "Wonderwall",
    accepted: ["wonderwall"],
    artist: "Oasis",
    era: "1990s",
    genre: "Britpop",
    firstLetters: "W",
    difficulty: "hard",
  },
  {
    id: 106,
    formal: "Methodology Of Gradual Biological Termination Via Melodic Vocal Narration Of Specific Biographical Data Pertaining Directly To The Listener",
    answer: "Killing Me Softly",
    accepted: ["killing me softly", "killing me softly with his song"],
    artist: "Roberta Flack / Fugees",
    era: "1970s",
    genre: "Soul / R&B",
    firstLetters: "K M S",
    difficulty: "hard",
  },
  {
    id: 107,
    formal: "The Ongoing Practice Of Habituating Oneself To A State Of Intensive Psychological Instability, Irrational Decision-Making, And Chaotic Interpersonal Conduct",
    answer: "Livin' La Vida Loca",
    accepted: ["livin la vida loca", "living la vida loca", "livin' la vida loca"],
    artist: "Ricky Martin",
    era: "1990s",
    genre: "Latin Pop",
    firstLetters: "L V L",
    difficulty: "hard",
  },
  {
    id: 108,
    formal: "Ocular Apparatus Of An Apex Predatory Feline, Employed As A Metaphorical Framework For Describing The Psychological State Of A Competitor Primed For Combat",
    answer: "Eye of the Tiger",
    accepted: ["eye of the tiger"],
    artist: "Survivor",
    era: "1980s",
    genre: "Rock",
    firstLetters: "E T",
    difficulty: "hard",
  },
  {
    id: 109,
    formal: "Universal Inclusive Classification Of Each Individual Member Of The Global Human Population As An Astronomical Body Of Significant Luminosity And Exceptional Character",
    answer: "All Star",
    accepted: ["all star", "allstar"],
    artist: "Smash Mouth",
    era: "1990s",
    genre: "Pop Rock",
    firstLetters: "A S",
    difficulty: "hard",
  },
  {
    id: 110,
    formal: "Informal Occupational Title Conferred Upon A Keyboard Percussion Operator Employed At A Licensed Peripatetic Tertiary Refreshment Establishment Catering To Emotionally Compromised Patrons",
    answer: "Piano Man",
    accepted: ["piano man"],
    artist: "Billy Joel",
    era: "1970s",
    genre: "Pop / Rock",
    firstLetters: "P M",
    difficulty: "hard",
  },
  {
    id: 111,
    formal: "Comprehensive Astronomical Obscuration Event Affecting The Primary Cardiac Muscle, Precipitating A State Of Extreme Emotional And Temporal Disorientation",
    answer: "Total Eclipse of the Heart",
    accepted: ["total eclipse of the heart"],
    artist: "Bonnie Tyler",
    era: "1980s",
    genre: "Power Ballad",
    firstLetters: "T E H",
    difficulty: "hard",
  },
  {
    id: 112,
    formal: "Extended Allegorical Balladic Account Of The Cessation Of Musical And Cultural Joy, Precipitated By A Catastrophic Aerial Transportation Incident Involving Several Prominent Musical Figures",
    answer: "American Pie",
    accepted: ["american pie"],
    artist: "Don McLean",
    era: "1970s",
    genre: "Folk Rock",
    firstLetters: "A P",
    difficulty: "hard",
  },
  {
    id: 113,
    formal: "Self-Identification As A Socially Deviant Individual Of Inadequate Personal Character, While Maintaining Geographical Proximity To An Unattainable Object Of Profound Unrequited Affection",
    answer: "Creep",
    accepted: ["creep"],
    artist: "Radiohead",
    era: "1990s",
    genre: "Alternative Rock",
    firstLetters: "C",
    difficulty: "hard",
  },
  {
    id: 114,
    formal: "Affective Declaration Of Territorial Allegiance, Nostalgic Affinity, And Cultural Pride Directed Toward A Specific Southern Administrative Region Of A Federal Constitutional Republic",
    answer: "Sweet Home Alabama",
    accepted: ["sweet home alabama"],
    artist: "Lynyrd Skynyrd",
    era: "1970s",
    genre: "Southern Rock",
    firstLetters: "S H A",
    difficulty: "hard",
  },
  {
    id: 115,
    formal: "Comparative Phenomenological Analysis Equating The Kinaesthetic Experience Of Romantic Locomotion With Established Devotional Supplication Practices Of Major World Religions",
    answer: "Like a Prayer",
    accepted: ["like a prayer"],
    artist: "Madonna",
    era: "1980s",
    genre: "Pop",
    firstLetters: "L P",
    difficulty: "hard",
  },
];

// ─── Daily puzzles ────────────────────────────────────────────────────────────
export const puzzles: Puzzle[] = [
  {
    id: 1,
    formal: "Meteorological Event In Which Adult Male Individuals Descend From Elevated Atmospheric Regions",
    answer: "It's Raining Men",
    accepted: ["its raining men", "it's raining men", "raining men"],
    artist: "The Weather Girls",
    era: "1980s",
    genre: "Disco / Pop",
    firstLetters: "I R M",
    difficulty: "easy",
  },
  {
    id: 2,
    formal: "Declaration Of Complete Emotional Liberation Achieved Following The Recipient's Extended Absence",
    answer: "Since U Been Gone",
    accepted: ["since u been gone", "since you been gone", "since you've been gone"],
    artist: "Kelly Clarkson",
    era: "2000s",
    genre: "Pop Rock",
    firstLetters: "S U B G",
    difficulty: "easy",
  },
  {
    id: 3,
    formal: "Earnest Petition For Return Transportation Via Rural Unpaved Thoroughfare To One's Ancestral Mountain Homeland",
    answer: "Take Me Home, Country Roads",
    accepted: ["take me home country roads", "country roads", "take me home"],
    artist: "John Denver",
    era: "1970s",
    genre: "Country / Folk",
    firstLetters: "T M H C R",
    difficulty: "medium",
  },
  {
    id: 4,
    formal: "Official Advance Report Confirming That A Bearded Gift-Distributing Individual Is Currently En Route To Your Residential Address",
    answer: "Santa Claus Is Comin' To Town",
    accepted: ["santa claus is coming to town", "santa claus is comin to town"],
    artist: "Various",
    era: "1930s",
    genre: "Christmas / Pop",
    firstLetters: "S C I C T T",
    difficulty: "easy",
  },
  {
    id: 5,
    formal: "Involuntary Cardiac Acceleration In Your Proximate Presence",
    answer: "Can't Help Falling in Love",
    accepted: ["cant help falling in love", "can't help falling in love"],
    artist: "Elvis Presley",
    era: "1960s",
    genre: "Pop / Soul",
    firstLetters: "C H F I L",
    difficulty: "medium",
  },
  {
    id: 6,
    formal: "Emphatic Prohibition Against Any Interference With The Speaker's Current State Of Uninhibited Recreational Enjoyment",
    answer: "Don't Stop Me Now",
    accepted: ["dont stop me now", "don't stop me now"],
    artist: "Queen",
    era: "1970s",
    genre: "Rock",
    firstLetters: "D S M N",
    difficulty: "easy",
  },
  {
    id: 7,
    formal: "Sincere Personal Attestation Of The Exceptional Beauty And Quality Of The Observed Natural World",
    answer: "What a Wonderful World",
    accepted: ["what a wonderful world"],
    artist: "Louis Armstrong",
    era: "1960s",
    genre: "Jazz / Pop",
    firstLetters: "W W W",
    difficulty: "easy",
  },
  {
    id: 8,
    formal: "Directive To Perform Manual Percussion If The Listener Concurs That Joy Constitutes An Objective And Verifiable State Of Being",
    answer: "Happy",
    accepted: ["happy"],
    artist: "Pharrell Williams",
    era: "2010s",
    genre: "Pop / Soul",
    firstLetters: "H",
    difficulty: "easy",
  },
  {
    id: 9,
    formal: "Hesitant Solicitation For The Recipient To Make Telephone Contact With The Speaker, Subject To Their Willingness To Do So",
    answer: "Call Me Maybe",
    accepted: ["call me maybe"],
    artist: "Carly Rae Jepsen",
    era: "2010s",
    genre: "Pop",
    firstLetters: "C M M",
    difficulty: "easy",
  },
  {
    id: 10,
    formal: "Directive To Dismiss Negative External Criticism Through Vigorous Lateral Displacement Of The Subject In Question",
    answer: "Shake It Off",
    accepted: ["shake it off"],
    artist: "Taylor Swift",
    era: "2010s",
    genre: "Pop",
    firstLetters: "S I O",
    difficulty: "easy",
  },
  {
    id: 11,
    formal: "Emphatic First-Person Declaration Of Continued Emotional And Biological Endurance Following The Unwanted Dissolution Of A Romantic Partnership",
    answer: "I Will Survive",
    accepted: ["i will survive"],
    artist: "Gloria Gaynor",
    era: "1970s",
    genre: "Disco",
    firstLetters: "I W S",
    difficulty: "easy",
  },
  {
    id: 12,
    formal: "Account Of Two Under-Resourced Individuals Sustaining Their Relationship Entirely On Hope And Supplication To A Higher Deity",
    answer: "Living on a Prayer",
    accepted: ["living on a prayer", "livin on a prayer", "livin' on a prayer"],
    artist: "Bon Jovi",
    era: "1980s",
    genre: "Rock",
    firstLetters: "L O A P",
    difficulty: "medium",
  },
  {
    id: 13,
    formal: "Solicitation For Vocal Accompaniment In Interpersonal Crisis Management",
    answer: "With a Little Help from My Friends",
    accepted: ["with a little help from my friends"],
    artist: "The Beatles",
    era: "1960s",
    genre: "Rock / Pop",
    firstLetters: "W L H F M F",
    difficulty: "medium",
  },
  {
    id: 14,
    formal: "Joyful Announcement Of The Imminent Arrival Of The Nearest Star Following A Long Period Of Cold And Darkness",
    answer: "Here Comes The Sun",
    accepted: ["here comes the sun"],
    artist: "The Beatles",
    era: "1960s",
    genre: "Rock / Pop",
    firstLetters: "H C S",
    difficulty: "easy",
  },
  {
    id: 15,
    formal: "Oscillatory Bodily Movements Performed In The Absence Of Adequate Lighting Conditions",
    answer: "Dancing In The Dark",
    accepted: ["dancing in the dark"],
    artist: "Bruce Springsteen",
    era: "1980s",
    genre: "Rock",
    firstLetters: "D I D",
    difficulty: "medium",
  },
  {
    id: 16,
    formal: "Solicitation For Protective Shelter Under A Portable Waterproof Canopy During Atmospheric Precipitation",
    answer: "Umbrella",
    accepted: ["umbrella"],
    artist: "Rihanna",
    era: "2000s",
    genre: "R&B / Pop",
    firstLetters: "U",
    difficulty: "easy",
  },
  {
    id: 17,
    formal: "Mandatory Communal Rhythmic Movement Required Of All Individuals Currently Present",
    answer: "Everybody Dance Now",
    accepted: ["everybody dance now", "gonna make you sweat everybody dance now"],
    artist: "C+C Music Factory",
    era: "1990s",
    genre: "Dance / House",
    firstLetters: "E D N",
    difficulty: "medium",
  },
  {
    id: 18,
    formal: "Categorical Refusal To Ever Abandon, Deceive, Or Emotionally Withdraw From The Recipient",
    answer: "Never Gonna Give You Up",
    accepted: ["never gonna give you up", "never going to give you up"],
    artist: "Rick Astley",
    era: "1980s",
    genre: "Pop",
    firstLetters: "N G G Y U",
    difficulty: "easy",
  },
  {
    id: 19,
    formal: "Affirmative Declaration Of Sustained Romantic Devotion To Be Maintained In Perpetuity",
    answer: "I Will Always Love You",
    accepted: ["i will always love you", "i'll always love you"],
    artist: "Whitney Houston",
    era: "1990s",
    genre: "R&B / Pop",
    firstLetters: "I W A L Y",
    difficulty: "easy",
  },
  {
    id: 20,
    formal: "Urgent Directive Issued To A Male Individual To Immediately Vacate The Premises And Avoid An Imminent Physical Altercation",
    answer: "Beat It",
    accepted: ["beat it"],
    artist: "Michael Jackson",
    era: "1980s",
    genre: "Pop / Rock",
    firstLetters: "B I",
    difficulty: "medium",
  },
  {
    id: 21,
    formal: "Auditory Simulation Of Ceremonial Resonating Bell Structures During The Festive Winter Season",
    answer: "Jingle Bells",
    accepted: ["jingle bells"],
    artist: "Traditional",
    era: "1800s",
    genre: "Christmas / Traditional",
    firstLetters: "J B",
    difficulty: "easy",
  },
  {
    id: 22,
    formal: "Personal Declaration That One Was Predestined From Birth To Engage In High-Velocity Ambulatory Pursuit Of Freedom",
    answer: "Born To Run",
    accepted: ["born to run"],
    artist: "Bruce Springsteen",
    era: "1970s",
    genre: "Rock",
    firstLetters: "B T R",
    difficulty: "medium",
  },
  {
    id: 23,
    formal: "Persistent Psychological Torment Inflicted By The Lingering Memory Of A Departed Romantic Partner",
    answer: "Someone Like You",
    accepted: ["someone like you"],
    artist: "Adele",
    era: "2010s",
    genre: "Pop / Soul",
    firstLetters: "S L Y",
    difficulty: "medium",
  },
  {
    id: 24,
    formal: "Formal Conferral Of Supreme Rhythmic Sovereignty Upon A Young Female Individual Aged Seventeen On A Friday Evening",
    answer: "Dancing Queen",
    accepted: ["dancing queen"],
    artist: "ABBA",
    era: "1970s",
    genre: "Pop / Disco",
    firstLetters: "D Q",
    difficulty: "medium",
  },
  {
    id: 25,
    formal: "Proposition To Conduct Oneself In A Manner Consistent With Equine Transportation Along A Rural Historic Route",
    answer: "Old Town Road",
    accepted: ["old town road", "take my horse to the old town road"],
    artist: "Lil Nas X",
    era: "2010s",
    genre: "Country Trap / Hip-Hop",
    firstLetters: "O T R",
    difficulty: "medium",
  },
  {
    id: 26,
    formal: "Persistent Gravitational Force Compelling Repeated Involuntary Descent To Ground Level",
    answer: "Falling",
    accepted: ["falling", "keep on falling"],
    artist: "Harry Styles",
    era: "2010s",
    genre: "Pop / Rock",
    firstLetters: "F",
    difficulty: "hard",
  },
  {
    id: 27,
    formal: "Directive To Release, Relinquish, And Allow The Situation To Proceed Without Further Attempt At Control",
    answer: "Let It Go",
    accepted: ["let it go"],
    artist: "Idina Menzel",
    era: "2010s",
    genre: "Soundtrack / Pop",
    firstLetters: "L I G",
    difficulty: "easy",
  },
  {
    id: 28,
    formal: "Enthusiastic Proposal To Engage In Rhythmic Musical Activity Continuously Throughout The Entire Twenty-Four Hour Temporal Cycle",
    answer: "Rock Around The Clock",
    accepted: ["rock around the clock", "we're gonna rock around the clock"],
    artist: "Bill Haley & His Comets",
    era: "1950s",
    genre: "Rock and Roll",
    firstLetters: "R A C",
    difficulty: "hard",
  },
  {
    id: 29,
    formal: "State Of Romantic Infatuation So Intense It Has Demonstrably Impaired The Subject's Rational Cognitive Faculties",
    answer: "Crazy In Love",
    accepted: ["crazy in love"],
    artist: "Beyoncé",
    era: "2000s",
    genre: "R&B / Pop",
    firstLetters: "C I L",
    difficulty: "easy",
  },
  {
    id: 30,
    formal: "Longitudinal Traversal Of A Narrow Pedestrian Infrastructure In The Specified Manner",
    answer: "Walk This Way",
    accepted: ["walk this way"],
    artist: "Aerosmith / Run DMC",
    era: "1970s",
    genre: "Rock / Hip-Hop",
    firstLetters: "W T W",
    difficulty: "medium",
  },
  {
    id: 31,
    formal: "Exclamatory Declaration Regarding An Exceptionally Large And Impressive Configuration Of Combusting Spherical Matter",
    answer: "Great Balls Of Fire",
    accepted: ["great balls of fire"],
    artist: "Jerry Lee Lewis",
    era: "1950s",
    genre: "Rock and Roll",
    firstLetters: "G B F",
    difficulty: "medium",
  },
  {
    id: 32,
    formal: "Emotional Entreaty For A Trusted Companion To Remain Physically Present During Times Of Personal Darkness And Fear",
    answer: "Stand By Me",
    accepted: ["stand by me"],
    artist: "Ben E. King",
    era: "1960s",
    genre: "Soul / R&B",
    firstLetters: "S B M",
    difficulty: "easy",
  },
  {
    id: 33,
    formal: "Grand Ascending Architectural Structure Of Sequential Steps Providing Progressive Access To The Celestial Afterlife",
    answer: "Stairway To Heaven",
    accepted: ["stairway to heaven"],
    artist: "Led Zeppelin",
    era: "1970s",
    genre: "Rock",
    firstLetters: "S T H",
    difficulty: "medium",
  },
  {
    id: 34,
    formal: "Atmospheric Particulate Matter Carried And Displaced By A Tempestuous Breeze",
    answer: "Dust In The Wind",
    accepted: ["dust in the wind"],
    artist: "Kansas",
    era: "1970s",
    genre: "Rock",
    firstLetters: "D I W",
    difficulty: "medium",
  },
  {
    id: 35,
    formal: "Romantic Petition For Immediate Aerial Transportation To The Nearest Lunar Satellite And Adjacent Celestial Bodies",
    answer: "Fly Me To The Moon",
    accepted: ["fly me to the moon"],
    artist: "Frank Sinatra",
    era: "1960s",
    genre: "Jazz / Pop",
    firstLetters: "F M T M",
    difficulty: "medium",
  },
  {
    id: 36,
    formal: "Sincere Invitation To Utilise The Speaker As A Physical And Emotional Support Structure During Periods Of Personal Adversity",
    answer: "Lean on Me",
    accepted: ["lean on me"],
    artist: "Bill Withers",
    era: "1970s",
    genre: "Soul / R&B",
    firstLetters: "L M",
    difficulty: "easy",
  },
  {
    id: 37,
    formal: "Regulatory Prohibition Against Unsolicited Emotional Precipitation Emanating From The Cardiac Region",
    answer: "Stop Crying Your Heart Out",
    accepted: ["stop crying your heart out"],
    artist: "Oasis",
    era: "2000s",
    genre: "Rock / Britpop",
    firstLetters: "S C Y H O",
    difficulty: "hard",
  },
  {
    id: 38,
    formal: "Olfactory Sensation Characteristic Of Adolescent Rebellious Spirit",
    answer: "Smells Like Teen Spirit",
    accepted: ["smells like teen spirit"],
    artist: "Nirvana",
    era: "1990s",
    genre: "Grunge / Rock",
    firstLetters: "S L T S",
    difficulty: "easy",
  },
  {
    id: 39,
    formal: "Geographic Inquiry Directed At The Current Domicile Of Interpersonal Affection",
    answer: "Where Is The Love",
    accepted: ["where is the love"],
    artist: "The Black Eyed Peas",
    era: "2000s",
    genre: "Hip-Hop / R&B",
    firstLetters: "W I T L",
    difficulty: "easy",
  },
  {
    id: 40,
    formal: "Self-Description As A Famished Predatory Canine, Employed As A Metaphor For The Speaker's Relentless Instinct-Driven Romantic Pursuit",
    answer: "Hungry Like the Wolf",
    accepted: ["hungry like the wolf"],
    artist: "Duran Duran",
    era: "1980s",
    genre: "New Wave / Pop",
    firstLetters: "H L W",
    difficulty: "hard",
  },
  {
    id: 41,
    formal: "Mandatory Relocation Of Physical Self To A Geographically Superior And Elevated Position",
    answer: "Higher Ground",
    accepted: ["higher ground"],
    artist: "Stevie Wonder",
    era: "1970s",
    genre: "R&B / Soul",
    firstLetters: "H G",
    difficulty: "medium",
  },
  {
    id: 42,
    formal: "Imperative Request For A Brief Instance Of Bilateral Oral Contact As An Act Of Interpersonal Affection",
    answer: "Kiss",
    accepted: ["kiss"],
    artist: "Prince",
    era: "1980s",
    genre: "Funk / Pop",
    firstLetters: "K",
    difficulty: "hard",
  },
  {
    id: 43,
    formal: "Buoyant Perambulation Atop Concentrated Solar Radiation, Accompanied By An Overwhelming Sensation Of Newly Discovered Romantic Joy",
    answer: "Walking On Sunshine",
    accepted: ["walking on sunshine"],
    artist: "Katrina And The Waves",
    era: "1980s",
    genre: "Pop / Rock",
    firstLetters: "W O S",
    difficulty: "easy",
  },
  {
    id: 44,
    formal: "Enthusiastic Endorsement Of The Continued Prosperous Existence Of A Glittering Illuminated Desert Gambling City",
    answer: "Viva Las Vegas",
    accepted: ["viva las vegas"],
    artist: "Elvis Presley",
    era: "1960s",
    genre: "Pop / Rock",
    firstLetters: "V L V",
    difficulty: "easy",
  },
  {
    id: 45,
    formal: "Narrative Of Romantic Betrayal Accompanied By The Speaker's Immersion In The Profound Emotional Depths Of Grief And Anger",
    answer: "Rolling In The Deep",
    accepted: ["rolling in the deep"],
    artist: "Adele",
    era: "2010s",
    genre: "Soul / Pop",
    firstLetters: "R I D",
    difficulty: "easy",
  },
  {
    id: 46,
    formal: "Formal Notification That Atmospheric Precipitation Is Once Again Imminent, Arriving Like An Unwanted Emotional Memory",
    answer: "Here Comes The Rain Again",
    accepted: ["here comes the rain again"],
    artist: "Eurythmics",
    era: "1980s",
    genre: "Synth-Pop",
    firstLetters: "H C R A",
    difficulty: "medium",
  },
  {
    id: 47,
    formal: "Instruction To Adopt The Stylised Laterally-Angled Pedestrian Posture Depicted In Ancient North African Hieroglyphic Art",
    answer: "Walk Like An Egyptian",
    accepted: ["walk like an egyptian"],
    artist: "The Bangles",
    era: "1980s",
    genre: "Pop / Rock",
    firstLetters: "W L E",
    difficulty: "easy",
  },
  {
    id: 48,
    formal: "Freshly Issued Personal Regulatory Code Governing The Speaker's Behaviour Following The Termination Of A Romantic Relationship",
    answer: "New Rules",
    accepted: ["new rules"],
    artist: "Dua Lipa",
    era: "2010s",
    genre: "Pop",
    firstLetters: "N R",
    difficulty: "medium",
  },
  {
    id: 49,
    formal: "Nocturnal Practice Of Enumerating Luminous Celestial Bodies As An Expression Of Aspirational Longing And Spiritual Restlessness",
    answer: "Counting Stars",
    accepted: ["counting stars"],
    artist: "OneRepublic",
    era: "2010s",
    genre: "Pop / Rock",
    firstLetters: "C S",
    difficulty: "medium",
  },
  {
    id: 50,
    formal: "Persistent Imperative To Maintain Continuous Forward Momentum Regardless Of All External Obstacles",
    answer: "Keep On Movin'",
    accepted: ["keep on movin", "keep on moving", "keep on movin'"],
    artist: "Soul II Soul",
    era: "1980s",
    genre: "R&B / Soul",
    firstLetters: "K O M",
    difficulty: "medium",
  },
  {
    id: 51,
    formal: "Theatrical Dramatic Confession From A Free-Spirited Individual Who Has Committed An Unspecified Capital Crime And Must Confront Its Consequences",
    answer: "Bohemian Rhapsody",
    accepted: ["bohemian rhapsody"],
    artist: "Queen",
    era: "1970s",
    genre: "Rock / Opera",
    firstLetters: "B R",
    difficulty: "hard",
  },
  {
    id: 52,
    formal: "Persistent Involuntary Mental Transportation To A Warm Sunlit West Coast State, Experienced During Cold Grey Winter Conditions",
    answer: "California Dreamin'",
    accepted: ["california dreamin", "california dreaming", "california dreamin'"],
    artist: "The Mamas & The Papas",
    era: "1960s",
    genre: "Folk Rock / Pop",
    firstLetters: "C D",
    difficulty: "medium",
  },
  {
    id: 53,
    formal: "Steadfast Prohibition Against The Cessation Of One's Fundamental Hope And Faith In The Possibility Of A Better Future",
    answer: "Don't Stop Believin'",
    accepted: ["dont stop believin", "don't stop believin", "don't stop believing"],
    artist: "Journey",
    era: "1980s",
    genre: "Rock",
    firstLetters: "D S B",
    difficulty: "easy",
  },
  {
    id: 54,
    formal: "Optimistic Enumeration Of Personally Preferred Sensory Experiences, Compiled As A Coping Mechanism For Fear And Sadness",
    answer: "My Favorite Things",
    accepted: ["my favorite things", "my favourite things"],
    artist: "Julie Andrews",
    era: "1960s",
    genre: "Soundtrack / Pop",
    firstLetters: "M F T",
    difficulty: "medium",
  },
  {
    id: 55,
    formal: "Official Supplication To The Almighty For The Protection And Preservation Of The Reigning Sovereign",
    answer: "God Save The King",
    accepted: ["god save the king", "god save the queen"],
    artist: "Traditional",
    era: "Various",
    genre: "Anthem / Traditional",
    firstLetters: "G S K",
    difficulty: "easy",
  },
  {
    id: 56,
    formal: "Expansive Natural Waterway Named After The Lunar Satellite, To Be Crossed In Partnership With A Like-Minded Companion Pursuing Life's Wonders",
    answer: "Moon River",
    accepted: ["moon river"],
    artist: "Henry Mancini / Audrey Hepburn",
    era: "1960s",
    genre: "Jazz / Soundtrack",
    firstLetters: "M R",
    difficulty: "hard",
  },
  {
    id: 57,
    formal: "Heartfelt Request For A Companion To Remain Present And Not Depart On This Particular Evening",
    answer: "Stay With Me",
    accepted: ["stay with me"],
    artist: "Sam Smith",
    era: "2010s",
    genre: "Soul / Pop",
    firstLetters: "S W M",
    difficulty: "easy",
  },
  {
    id: 58,
    formal: "Solemn Vow To Preserve One's Affection For An Individual Regardless Of Distance Or Circumstance",
    answer: "No Matter What",
    accepted: ["no matter what"],
    artist: "Boyzone",
    era: "1990s",
    genre: "Pop",
    firstLetters: "N M W",
    difficulty: "medium",
  },
  {
    id: 59,
    formal: "Traditional Communal Vocalisation Conveying Celebratory Greetings To An Individual On The Annual Anniversary Of Their Birth",
    answer: "Happy Birthday To You",
    accepted: ["happy birthday to you", "happy birthday"],
    artist: "Traditional",
    era: "1900s",
    genre: "Traditional",
    firstLetters: "H B T Y",
    difficulty: "easy",
  },
  {
    id: 60,
    formal: "Official Report That A Royal Authority Has Ordered The Musical Disruption Of A Fortified North African Citadel, Against The Wishes Of The Local Populace",
    answer: "Rock The Casbah",
    accepted: ["rock the casbah"],
    artist: "The Clash",
    era: "1980s",
    genre: "Punk / Rock",
    firstLetters: "R C",
    difficulty: "medium",
  },
  {
    id: 61,
    formal: "Atmospheric Precipitation In An Unconventional Royal Chromatic Hue, Serving As Metaphor For Emotional Sacrifice And Transcendent Love",
    answer: "Purple Rain",
    accepted: ["purple rain"],
    artist: "Prince",
    era: "1980s",
    genre: "Pop / Rock",
    firstLetters: "P R",
    difficulty: "hard",
  },
  {
    id: 62,
    formal: "Declaration That The Speaker's Cardiac Organ Shall Continue Its Emotional Operations Indefinitely Despite The Recipient's Departure",
    answer: "My Heart Will Go On",
    accepted: ["my heart will go on"],
    artist: "Celine Dion",
    era: "1990s",
    genre: "Pop / Ballad",
    firstLetters: "M H W G O",
    difficulty: "easy",
  },
  {
    id: 63,
    formal: "Romantic Offer Of The Speaker's Complete And Undivided Totality To The Recipient, Including All Imperfections",
    answer: "All of Me",
    accepted: ["all of me"],
    artist: "John Legend",
    era: "2010s",
    genre: "R&B / Pop",
    firstLetters: "A M",
    difficulty: "easy",
  },
  {
    id: 64,
    formal: "Proclamation Of Exceptional Structural Invulnerability Named After The Lightest And Strongest Commercially Available Metallic Element",
    answer: "Titanium",
    accepted: ["titanium"],
    artist: "David Guetta ft. Sia",
    era: "2010s",
    genre: "Electronic / Pop",
    firstLetters: "T",
    difficulty: "hard",
  },
  {
    id: 65,
    formal: "State Of Romantic Intoxication So Extreme That The Subject's Normal Rational Faculties Have Been Entirely Compromised By Passion",
    answer: "Drunk In Love",
    accepted: ["drunk in love"],
    artist: "Beyoncé",
    era: "2010s",
    genre: "R&B / Pop",
    firstLetters: "D I L",
    difficulty: "medium",
  },

  // ── Easy additions ────────────────────────────────────────────
  {
    id: 66,
    formal: "Astronomical Colour Classification Assigned To Luminous Celestial Bodies, Applied As A Term Of Devotion To A Cherished Individual",
    answer: "Yellow",
    accepted: ["yellow"],
    artist: "Coldplay",
    era: "2000s",
    genre: "Pop / Rock",
    firstLetters: "Y",
    difficulty: "easy",
  },
  {
    id: 67,
    formal: "Stated Intention To Restore Optimal Functional Capacity To A Damaged Or Emotionally Malfunctioning Individual",
    answer: "Fix You",
    accepted: ["fix you"],
    artist: "Coldplay",
    era: "2000s",
    genre: "Pop / Rock",
    firstLetters: "F Y",
    difficulty: "easy",
  },
  {
    id: 68,
    formal: "Imperative Directive Instructing The Speaker To Release And Cease Retaining A Female Individual",
    answer: "Let Her Go",
    accepted: ["let her go"],
    artist: "Passenger",
    era: "2010s",
    genre: "Folk / Pop",
    firstLetters: "L H G",
    difficulty: "easy",
  },
  {
    id: 69,
    formal: "Underwater Naval Vessel Of A Chromatic Yellow Hue, Jointly Occupied By A Cohesive Group Of Associated Individuals",
    answer: "Yellow Submarine",
    accepted: ["yellow submarine"],
    artist: "The Beatles",
    era: "1960s",
    genre: "Rock / Pop",
    firstLetters: "Y S",
    difficulty: "easy",
  },
  {
    id: 70,
    formal: "Informal Oral Claim Upon The Preferred Front Passenger Seat Within A Motor Vehicle",
    answer: "Shotgun",
    accepted: ["shotgun"],
    artist: "George Ezra",
    era: "2010s",
    genre: "Pop",
    firstLetters: "S",
    difficulty: "easy",
  },

  // ── Medium additions ──────────────────────────────────────────
  {
    id: 71,
    formal: "Practice Of Externalising Internal Cognitive Deliberations In Vocal Form Within The Context Of An Enduring Romantic Commitment",
    answer: "Thinking Out Loud",
    accepted: ["thinking out loud"],
    artist: "Ed Sheeran",
    era: "2010s",
    genre: "Pop / Soul",
    firstLetters: "T O L",
    difficulty: "medium",
  },
  {
    id: 72,
    formal: "Interrogative Inquiry Into Whether The Addressee Is Capable Of Operating Below The Surface Level Of Emotional Experience",
    answer: "Shallow",
    accepted: ["shallow"],
    artist: "Lady Gaga & Bradley Cooper",
    era: "2010s",
    genre: "Pop / Country",
    firstLetters: "S",
    difficulty: "medium",
  },
  {
    id: 73,
    formal: "Celestial Winged Intermediary Beings Invoked As Protective Companions During Periods Of Personal Difficulty",
    answer: "Angels",
    accepted: ["angels"],
    artist: "Robbie Williams",
    era: "1990s",
    genre: "Pop",
    firstLetters: "A",
    difficulty: "medium",
  },
  {
    id: 74,
    formal: "Solitary Ambulatory Transit Along An Urban Thoroughfare Lined With The Remnants Of Failed Aspirations",
    answer: "Boulevard of Broken Dreams",
    accepted: ["boulevard of broken dreams"],
    artist: "Green Day",
    era: "2000s",
    genre: "Punk Rock",
    firstLetters: "B B D",
    difficulty: "medium",
  },

  // ── Hard additions ────────────────────────────────────────────
  {
    id: 75,
    formal: "Reclassification Of A Previously Intimate Associate To The Status Of An Unrecognised Member Of The General Population",
    answer: "Somebody That I Used to Know",
    accepted: ["somebody that i used to know"],
    artist: "Gotye ft. Kimbra",
    era: "2010s",
    genre: "Indie Pop",
    firstLetters: "S I U K",
    difficulty: "hard",
  },
  {
    id: 76,
    formal: "Biochemically Hazardous Compound Introduced Via Romantic Interaction, Producing Progressive Physiological And Psychological Deterioration",
    answer: "Toxic",
    accepted: ["toxic"],
    artist: "Britney Spears",
    era: "2000s",
    genre: "Pop",
    firstLetters: "T",
    difficulty: "hard",
  },
  {
    id: 77,
    formal: "Categorisation Of An Interpersonal Attachment As Fundamentally Defective, Paradoxically Combined With Voluntary Re-Engagement In Said Attachment",
    answer: "Bad Romance",
    accepted: ["bad romance"],
    artist: "Lady Gaga",
    era: "2000s",
    genre: "Pop / Electronic",
    firstLetters: "B R",
    difficulty: "hard",
  },
  {
    id: 78,
    formal: "Extreme Photonic Stimulation Of The Ocular System During Nocturnal Urban Transit, Causing Temporary Impairment Of Visual Perception",
    answer: "Blinding Lights",
    accepted: ["blinding lights"],
    artist: "The Weeknd",
    era: "2010s",
    genre: "Synth-Pop",
    firstLetters: "B L",
    difficulty: "hard",
  },
  {
    id: 79,
    formal: "Topographical Survey Of The Anatomical Contours Of A Specific Individual Designated As The Primary Object Of Aesthetic And Romantic Appreciation",
    answer: "Shape of You",
    accepted: ["shape of you"],
    artist: "Ed Sheeran",
    era: "2010s",
    genre: "Pop",
    firstLetters: "S Y",
    difficulty: "hard",
  },
  {
    id: 80,
    formal: "Historical Battle Site Repurposed As Metaphor For The Definitive Capitulation Of An Individual's Romantic Resistance To A Persistent Suitor",
    answer: "Waterloo",
    accepted: ["waterloo"],
    artist: "ABBA",
    era: "1970s",
    genre: "Pop",
    firstLetters: "W",
    difficulty: "hard",
  },
  {
    id: 81,
    formal: "Repeated Invocation Of A Female Parental Figure Upon The Surprise Re-Appearance Of A Previously Dismissed Former Romantic Partner",
    answer: "Mamma Mia",
    accepted: ["mamma mia"],
    artist: "ABBA",
    era: "1970s",
    genre: "Pop",
    firstLetters: "M M",
    difficulty: "hard",
  },
  {
    id: 82,
    formal: "Regulatory Principle Stipulating That The Victorious Party In A Competition Acquires Exclusive Entitlement To All Available Prizes",
    answer: "The Winner Takes It All",
    accepted: ["the winner takes it all", "winner takes it all"],
    artist: "ABBA",
    era: "1980s",
    genre: "Pop",
    firstLetters: "W T I A",
    difficulty: "hard",
  },
  {
    id: 83,
    formal: "Imperative Solicitation For An Individual To Willingly Accept The Speaker's Romantic Challenge",
    answer: "Take On Me",
    accepted: ["take on me"],
    artist: "a-ha",
    era: "1980s",
    genre: "Synth-Pop",
    firstLetters: "T O M",
    difficulty: "hard",
  },
  {
    id: 84,
    formal: "Terminal Sequential Numerical Reduction Preceding An Event Of Great Personal Or Collective Consequence",
    answer: "The Final Countdown",
    accepted: ["the final countdown", "final countdown"],
    artist: "Europe",
    era: "1980s",
    genre: "Hard Rock",
    firstLetters: "F C",
    difficulty: "hard",
  },
  {
    id: 85,
    formal: "Affectionate Address To A Juvenile Individual Whose Physical Characteristics Evoke Powerful Nostalgic And Romantic Associations In The Speaker",
    answer: "Sweet Child O' Mine",
    accepted: ["sweet child o mine", "sweet child of mine", "sweet child o' mine"],
    artist: "Guns N' Roses",
    era: "1980s",
    genre: "Rock",
    firstLetters: "S C M",
    difficulty: "hard",
  },
  {
    id: 86,
    formal: "Atmospheric Precipitation Occurring In The Penultimate Calendar Month, Functioning As Extended Metaphor For The Progressive Deterioration Of A Romantic Partnership",
    answer: "November Rain",
    accepted: ["november rain"],
    artist: "Guns N' Roses",
    era: "1990s",
    genre: "Rock / Ballad",
    firstLetters: "N R",
    difficulty: "hard",
  },
  {
    id: 87,
    formal: "Formal Greeting And Orientation Protocol Issued To Individuals Newly Arrived In An Environment Of Unregulated Competitive Predation",
    answer: "Welcome to the Jungle",
    accepted: ["welcome to the jungle"],
    artist: "Guns N' Roses",
    era: "1980s",
    genre: "Hard Rock",
    firstLetters: "W J",
    difficulty: "hard",
  },
  {
    id: 88,
    formal: "Hypothetical Utopian Municipality Distinguished By Optimal Ground-Level Vegetation And A Population Of Exceptionally Attractive Female Residents",
    answer: "Paradise City",
    accepted: ["paradise city"],
    artist: "Guns N' Roses",
    era: "1980s",
    genre: "Hard Rock",
    firstLetters: "P C",
    difficulty: "hard",
  },
  {
    id: 89,
    formal: "Collective First-Person Declaration Of Competitive Supremacy Issued On Behalf Of A Victorious Group To The General Populace",
    answer: "We Are the Champions",
    accepted: ["we are the champions"],
    artist: "Queen",
    era: "1970s",
    genre: "Rock",
    firstLetters: "W A C",
    difficulty: "hard",
  },
  {
    id: 90,
    formal: "Nonsensical Repetitive Exclamations Directed At A Broadcast Audio Transmission Medium, Lamenting Its Gradual Displacement By Visual Technologies",
    answer: "Radio Ga Ga",
    accepted: ["radio ga ga", "radio gaga"],
    artist: "Queen",
    era: "1980s",
    genre: "Rock / Synth-Pop",
    firstLetters: "R G G",
    difficulty: "hard",
  },
  {
    id: 91,
    formal: "Rhythmically Sophisticated Musical Composition Originating From The Affluent Northern Quarter Of An Unspecified Metropolitan Area, Asserting Its Own Cultural Superiority",
    answer: "Uptown Funk",
    accepted: ["uptown funk"],
    artist: "Mark Ronson ft. Bruno Mars",
    era: "2010s",
    genre: "Funk / Pop",
    firstLetters: "U F",
    difficulty: "hard",
  },
  {
    id: 92,
    formal: "Unilateral Verbal Expression Of Remorse And Contrition Tendered To An Individual Who Sustained Harm Due To The Speaker's Prior Conduct",
    answer: "Sorry",
    accepted: ["sorry"],
    artist: "Justin Bieber",
    era: "2010s",
    genre: "Pop",
    firstLetters: "S",
    difficulty: "hard",
  },
  {
    id: 93,
    formal: "Therapeutic Directive Encouraging An Individual To Redirect Misallocated External Affection Inward As Unsolicited Counsel To A Former Partner",
    answer: "Love Yourself",
    accepted: ["love yourself"],
    artist: "Justin Bieber",
    era: "2010s",
    genre: "Pop",
    firstLetters: "L Y",
    difficulty: "hard",
  },
  {
    id: 94,
    formal: "Incremental Directive For The Progressive Deceleration Of All Aspects Of An Interpersonal Encounter To The Minimum Viable Operational Velocity",
    answer: "Despacito",
    accepted: ["despacito"],
    artist: "Luis Fonsi ft. Daddy Yankee",
    era: "2010s",
    genre: "Latin Pop / Reggaeton",
    firstLetters: "D",
    difficulty: "hard",
  },
  {
    id: 95,
    formal: "Interrogative Challenge Directed At A Former Partner Regarding Whether They Retain Any Residual Desire For The Speaker's Companionship",
    answer: "Don't You Want Me",
    accepted: ["dont you want me", "don't you want me"],
    artist: "The Human League",
    era: "1980s",
    genre: "Synth-Pop",
    firstLetters: "D Y W M",
    difficulty: "hard",
  },
  {
    id: 96,
    formal: "Urgent Entreaty Directed At A Named Female Individual To Respond Favourably To The Speaker's Romantic Overtures At This Juncture",
    answer: "Come On Eileen",
    accepted: ["come on eileen"],
    artist: "Dexys Midnight Runners",
    era: "1980s",
    genre: "Pop / Celtic",
    firstLetters: "C E",
    difficulty: "hard",
  },
  {
    id: 97,
    formal: "Formal Declaration Of Romantic Interest In The Primary Maternal Guardian Of A Named Female Acquaintance Rather Than Said Acquaintance Herself",
    answer: "Stacy's Mom",
    accepted: ["stacys mom", "stacy's mom"],
    artist: "Fountains of Wayne",
    era: "2000s",
    genre: "Power Pop",
    firstLetters: "S M",
    difficulty: "hard",
  },
  {
    id: 98,
    formal: "Nostalgic Address Directed At A Named Male Companion, Recalling A Shared Experience Of Armed Conflict Under Favourable Nocturnal Celestial Conditions",
    answer: "Fernando",
    accepted: ["fernando"],
    artist: "ABBA",
    era: "1970s",
    genre: "Pop",
    firstLetters: "F",
    difficulty: "hard",
  },
  {
    id: 99,
    formal: "Internationally Standardised Emergency Distress Signal Transmitted Under Conditions Of Acute Romantic Crisis",
    answer: "SOS",
    accepted: ["sos"],
    artist: "ABBA",
    era: "1970s",
    genre: "Pop",
    firstLetters: "S",
    difficulty: "hard",
  },
  {
    id: 100,
    formal: "Urgent Iterative Demand For The Immediate Provision Of An Adult Male Companion Following The Conclusion Of The Twelfth Nocturnal Hour",
    answer: "Gimme! Gimme! Gimme!",
    accepted: ["gimme gimme gimme"],
    artist: "ABBA",
    era: "1980s",
    genre: "Pop / Disco",
    firstLetters: "G G G",
    difficulty: "hard",
  },
  {
    id: 116,
    formal: "Collective Directive Requiring The Convergence Of Multiple Distinct And Disparate Parties Toward A Single Unified Purpose",
    answer: "Come Together",
    accepted: ["come together"],
    artist: "The Beatles",
    era: "1960s",
    genre: "Rock",
    firstLetters: "C T",
    difficulty: "hard",
  },
  {
    id: 117,
    formal: "Romantic Affection That Has Been Irreversibly Contaminated By External Forces, Rendering It Unsuitable For Continued Consumption",
    answer: "Tainted Love",
    accepted: ["tainted love"],
    artist: "Soft Cell",
    era: "1980s",
    genre: "Synth-Pop",
    firstLetters: "T L",
    difficulty: "hard",
  },
  {
    id: 118,
    formal: "Persistent Adherence To Irrational Beliefs Postulating A Causal Relationship Between Arbitrary Ritual Actions And Subsequent Real-World Events",
    answer: "Superstition",
    accepted: ["superstition"],
    artist: "Stevie Wonder",
    era: "1970s",
    genre: "Funk / Soul",
    firstLetters: "S",
    difficulty: "hard",
  },
  {
    id: 119,
    formal: "Documentation Of A Female Individual's Capacity To Induce Severe Psychological Disturbance In The Speaker Through Ordinary Daily Activities",
    answer: "She Drives Me Crazy",
    accepted: ["she drives me crazy"],
    artist: "Fine Young Cannibals",
    era: "1980s",
    genre: "Pop / R&B",
    firstLetters: "S D M C",
    difficulty: "hard",
  },
  {
    id: 120,
    formal: "Uncontaminated Cognitive Faculty For Generating Novel Mental Constructs That Transcend The Established Boundaries Of Physical Reality",
    answer: "Pure Imagination",
    accepted: ["pure imagination"],
    artist: "Gene Wilder",
    era: "1970s",
    genre: "Soundtrack / Pop",
    firstLetters: "P I",
    difficulty: "hard",
  },
];
